/**
 * data.js — Downtown Tampa: A Civic Development Autopsy
 * Complete cited data layer. Every data point carries a source object.
 *
 * CITATION PHILOSOPHY:
 *   - Population: U.S. Census Bureau decennial counts (citywide) and
 *     downtown-core residential estimates from Tampa Downtown Partnership /
 *     Census tract aggregates where noted
 *   - Port & trade: Port Tampa Bay / U.S. Army Corps / historical yearbooks
 *   - Urban form: City of Tampa planning records, Florida Memory photo archive,
 *     Library of Congress Sanborn maps, USF Digital Collections
 *   - All URLs point to the closest available archival or canonical source
 *   - Estimates are labeled; prefer primary institutional sources
 */

window.tampaData = {

  meta: { title: "Downtown Tampa: A Civic Development Autopsy", subtitle: "How a fort, a railroad, a cigar boom, urban renewal, and a waterfront remade the civic core of Tampa Bay", span: "1824 – 2024", years: 200, center: [27.9475, -82.4563], defaultZoom: 14 },

  cityPopulation: [
    { year: 1850, pop: 974, note: "Tampa settlement including the Fort Brooke garrison: 638 free persons + 336 enslaved; the Census Office omitted the aggregate as uncertain.",
      source: { institution: "U.S. Census Office, Seventh Census of the United States: 1850, Statistics of Florida, Table II", date: "1853",
        url: "https://www2.census.gov/library/publications/decennial/1850/1850a/1850-census-report-florida.pdf",
        note: "Not a municipal count. Printed cells: 631 white + 7 free colored = 638 free; 336 slaves (which the Office warned may include slaves owned but not living in the town). Hillsborough County as a whole was 2,377. The Bureau's own retrospective city series starts in 1870.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { year: 1870, pop: 796, note: "First decennial count for the town of Tampa in the Census Bureau's retrospective series.",
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Scanned PDF; Table 5 'Population of Incorporated Places of 10,000 or More from Earliest Census to 1960', p. 11-10.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1880, pop: 720, note: "Pre-Plant railroad; town shrank 9.5% during the 1870s.",
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 5: '1880 …… 720 | -76 | -9.5'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1890, pop: 5532, note: "After the Plant System railroad (1884) and Ybor City's founding (1886).",
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 5: '1890 …… 5,532 | 4,812 | 668.3'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1900, pop: 15839,
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 5: '1900 …… 15,839 | 10,307 | 186.3'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1910, pop: 37782,
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 5: '1910 …… 37,782 | 21,943 | 138.5'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1920, pop: 51608,
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 5: '1920 …… 51,608 | 13,826 | 36.6'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1930, pop: 101161, note: "Florida land-boom decade; city nearly doubles.",
      source: { institution: "U.S. Census Bureau, Population Division Working Paper POP-WP027 (Gibson 1998), Table 16", date: "1998-06-15",
        url: "https://www2.census.gov/library/working-papers/1998/demographics/pop-twps0027/tab16.txt",
        note: "'91 Tampa city, FL 101,161 19.0 5,324' — rank 91st, land area 19.0 sq mi.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1940, pop: 108391,
      source: { institution: "U.S. Census Bureau, POP-WP027 (Gibson 1998), Table 17", date: "1998-06-15",
        url: "https://www2.census.gov/library/working-papers/1998/demographics/pop-twps0027/tab17.txt",
        note: "'84 Tampa city, FL 108,391 19.0 5,705'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1950, pop: 124681, note: "Last census before the 1953 annexation act.",
      source: { institution: "U.S. Census Bureau, POP-WP027 (Gibson 1998), Table 18", date: "1998-06-15",
        url: "https://www2.census.gov/library/working-papers/1998/demographics/pop-twps0027/tab18.txt",
        note: "'85 Tampa city, FL 124,681 19.0 6,562'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1960, pop: 274970, note: "Annexation, not natural growth: 140,331 of the 274,970 (51%) lived in territory annexed 1950–60; the 1950 city limits grew only to 134,639.",
      source: { institution: "U.S. Bureau of the Census, 1960 Census of Population, Vol. I Pt. 11 Florida, Number of Inhabitants, Table 5 and Table 9", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        note: "Table 9 '1960 Population of Areas Annexed Between 1950 and 1960'. Land area 19.0 → 85.0 sq mi; national rank 85th → 48th (Gibson Table 19). Annexation instrument: Chapter 29548, Laws of Florida, Special Acts of 1953.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1970, pop: 277767,
      source: { institution: "U.S. Census Bureau, POP-WP027 (Gibson 1998), Table 20", date: "1998-06-15",
        url: "https://www2.census.gov/library/working-papers/1998/demographics/pop-twps0027/tab20.txt",
        note: "Count as originally published; later corrected to 277,714 in 1990 CPH-2-11 Table 9.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1980, pop: 271523, note: "Suburbanization: slight citywide decline while the county grows.",
      source: { institution: "U.S. Census Bureau, POP-WP027 (Gibson 1998), Table 21", date: "1998-06-15",
        url: "https://www2.census.gov/library/working-papers/1998/demographics/pop-twps0027/tab21.txt",
        note: "Count as originally published; revised to 271,577 in 1990 CPH-2-11 ('r271 577').",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1990, pop: 280015,
      source: { institution: "U.S. Bureau of the Census, 1990 CPH-2-11 Population and Housing Unit Counts, Florida, Tables 9–10", date: "1992",
        url: "https://www2.census.gov/library/publications/decennial/1990/cph-2/cph-2-11.pdf",
        note: "Land area 108.7 sq mi; 3rd-largest city in Florida.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2000, pop: 303447,
      source: { institution: "U.S. Census Bureau, Census 2000 PHC-3-11 Population and Housing Unit Counts, Florida, Table 7", date: "2003",
        url: "https://www2.census.gov/library/publications/2003/dec/phc-3-11.pdf",
        note: "Also data.census.gov SF1 P001 for place 1271000 (303,447). Land area 112.07 sq mi.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2010, pop: 335709,
      source: { institution: "U.S. Census Bureau, 2010 CPH-2-11 Population and Housing Unit Counts, Florida", date: "2012",
        url: "https://www2.census.gov/library/publications/decennial/2010/cph-2/cph-2-11.pdf",
        note: "Also data.census.gov 2010 SF1 P1: https://data.census.gov/table/DECENNIALSF12010.P1?g=160XX00US1271000",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2020, pop: 384959, note: "City of Tampa municipal population.",
      source: { institution: "U.S. Census Bureau, 2020 Census Redistricting Data (P.L. 94-171), Table P1, Tampa city", date: "2021",
        url: "https://data.census.gov/table/DECENNIALPL2020.P1?g=160XX00US1271000",
        note: "P1_001N = 384,959 (data.census.gov API).",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  /* Hillsborough County decennial counts — context for the city series. */
  countyPopulation: [
    { year: 1850, pop: 2377,
      source: { institution: "U.S. Census Office, Seventh Census 1850, Statistics of Florida, Table I", date: "1853",
        url: "https://www2.census.gov/library/publications/decennial/1850/1850a/1850-census-report-florida.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1860, pop: 2981,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1870, pop: 3216,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1880, pop: 5814,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1890, pop: 14941,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1900, pop: 36013,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1910, pop: 78374,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        note: "Pinellas County was carved out of Hillsborough in 1912, so 1910 → 1920 is not like-for-like.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1920, pop: 88257,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1930, pop: 153519,
      source: { institution: "U.S. Census Bureau, Population Division (Forstall), Population of States and Counties of the United States: 1790 to 1990", date: "1996",
        url: "https://www2.census.gov/library/publications/decennial/1990/population-of-states-and-counties-us-1790-1990/population-of-states-and-counties-of-the-united-states-1790-1990.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1940, pop: 180148,
      source: { institution: "U.S. Bureau of the Census, 1990 CPH-2-11 Florida, Table 3", date: "1992",
        url: "https://www2.census.gov/library/publications/decennial/1990/cph-2/cph-2-11.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1950, pop: 249894,
      source: { institution: "U.S. Bureau of the Census, 1960 Census Vol. I Pt. 11 Florida, Table 6", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1960, pop: 397788,
      source: { institution: "U.S. Bureau of the Census, 1960 Census Vol. I Pt. 11 Florida, Table 6", date: "1963",
        url: "https://www2.census.gov/library/publications/decennial/1960/population-volume-1/vol-01-11-c.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1970, pop: 490265,
      source: { institution: "U.S. Bureau of the Census, 1990 CPH-2-11 Florida, Table 3", date: "1992",
        url: "https://www2.census.gov/library/publications/decennial/1990/cph-2/cph-2-11.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1980, pop: 646939,
      source: { institution: "U.S. Bureau of the Census, 1990 CPH-2-11 Florida, Table 3", date: "1992",
        url: "https://www2.census.gov/library/publications/decennial/1990/cph-2/cph-2-11.pdf",
        note: "Revised count ('r646 939'); originally published 646,960.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1990, pop: 834054,
      source: { institution: "U.S. Bureau of the Census, 1990 CPH-2-11 Florida, Table 3", date: "1992",
        url: "https://www2.census.gov/library/publications/decennial/1990/cph-2/cph-2-11.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2000, pop: 998948,
      source: { institution: "U.S. Census Bureau, Census 2000 PHC-3-11 Florida, Table 2", date: "2003",
        url: "https://www2.census.gov/library/publications/2003/dec/phc-3-11.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2010, pop: 1229226,
      source: { institution: "U.S. Census Bureau, 2010 CPH-2-11 Florida, Table 4", date: "2012",
        url: "https://www2.census.gov/library/publications/decennial/2010/cph-2/cph-2-11.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2020, pop: 1459762,
      source: { institution: "U.S. Census Bureau, 2020 Census P.L. 94-171 Table P1, Hillsborough County", date: "2021",
        url: "https://data.census.gov/table/DECENNIALPL2020.P1?g=050XX00US12057",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  downtownResidents: [
    { year: 1900, residents: 8500, estimate: true,
      note: "Dense walk-up residential fabric mixed with retail along Franklin / Tampa St.",
      source: { institution: "Sanborn Map Co. via Library of Congress, Tampa 1899 and 1903 volumes", date: "1903",
        url: "https://www.loc.gov/item/sanborn01352_007/",
        note: "Editorial estimate read from Sanborn footprint density; not a census-tract total. Replace with NHGIS tract data when compiled.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { year: 1930, residents: 12000, estimate: true,
      note: "Peak mixed-use residential density before auto-era suburbanization.",
      source: { institution: "City of Tampa, Tampa History page", date: "1930",
        url: "https://www.tampa.gov/info/tampa-history",
        note: "Unverified planning-literature estimate; no tract series located yet.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1950, residents: 6000, estimate: true,
      note: "Postwar flight to suburbs begins hollowing the core.",
      source: { institution: "City of Tampa, Tampa History page", date: "1950",
        url: "https://www.tampa.gov/info/tampa-history",
        note: "Unverified estimate pending 1950 census-tract compilation.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1970, residents: 2500, estimate: true,
      note: "Urban renewal clearance and interstate construction remove residential stock.",
      source: { institution: "City of Tampa, Soulwalk historic marker: The Scrub", date: "1970",
        url: "https://www.tampa.gov/soulwalk/historic-markers/scrub",
        note: "Marker confirms the 1959 clearance and 1960s I-4/urban renewal; the resident count is an unverified estimate.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1980, residents: 1800, estimate: true,
      note: "Franklin Street Mall era — commercial focus, thin residential base.",
      source: { institution: "Tampa Downtown Partnership, downtown history", date: "1980",
        url: "https://www.tampasdowntown.com/about-us/history/",
        note: "Unverified estimate.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1990, residents: 3200, estimate: true,
      note: "Early condo conversions and Harbour Island residential growth (development completed 1985).",
      source: { institution: "Tampa Bay Times, Harbour Island history", date: "2019-01-25",
        url: "https://www.tampabay.com/hillsborough/when-only-their-family-lived-there-young-brothers-found-adventure-on-isolated-harbour-island-20190125/",
        note: "Harbour Island build-out confirmed; the 3,200 total is an unverified estimate.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2000, residents: 5000, estimate: true,
      note: "Channel District loft conversion wave begins.",
      source: { institution: "Tampa Downtown Partnership", date: "2000",
        url: "https://www.tampasdowntown.com/",
        note: "Unverified estimate.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2010, residents: 8494, estimate: false,
      note: "Tampa Downtown Partnership Special Services District boundary, 2010 Census.",
      source: { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        note: "Guide reports downtown residents 8,494 (2010) → 17,366 (2020) → ~23,600 (2025); ~11,000 residential units.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2017, residents: 10000, estimate: true,
      note: "TDP: downtown residential growth outpaced many peer emerging downtowns.",
      source: { institution: "Tampa Downtown Partnership, news", date: "2017",
        url: "https://www.tampasdowntown.com/news/tampas-downtown-strong-according-to-national-report/",
        note: "Round figure from a TDP news post; boundary differs from the 2010/2020 guide series.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2020, residents: 17366, estimate: false,
      note: "2020 Census count for the Tampa Downtown Partnership district.",
      source: { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        note: "'8,494 (2010) → 17,366 (2020)'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2025, residents: 23600, estimate: false,
      note: "Water Street, Channel District and Tampa Heights deliveries lift the core.",
      source: { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        note: "'approximately 23,600 residents' (2025 estimate in the guide).",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  portActivity: [
    { year: 1888, index: 12, cargoNote: "Early deepwater dredging; Plant steamship connections",
      source: { date: "1888", institution: "Port Tampa Bay / Florida Memory", url: "https://www.floridamemory.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1900, index: 35, cargoNote: "Cigar leaf imports + coastal trade",
      source: { date: "1900", institution: "Port of Tampa historical yearbooks", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1915, index: 55, cargoNote: "Phosphate export expansion",
      source: { date: "1915", institution: "U.S. Army Corps of Engineers / Port histories", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1925, index: 100, cargoNote: "Phosphate export peak era; major Gulf port",
      source: { date: "1925", institution: "Port Tampa Bay histories", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1943, index: 88, cargoNote: "WWII shipbuilding and military logistics",
      source: { date: "1943", institution: "U.S. Navy / local WWII industrial records", url: "https://www.floridamemory.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1960, index: 70, cargoNote: "Bulk commodities; downtown waterfront still industrial",
      source: { date: "1960", institution: "Port Tampa Bay", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1980, index: 75, cargoNote: "Containerization begins shifting activity seaward of CBD",
      source: { date: "1980", institution: "Port Tampa Bay", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2000, index: 90, cargoNote: "Diversified bulk, cruise, and general cargo",
      source: { date: "2000", institution: "Port Tampa Bay", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2010, index: 95, cargoNote: "Cruise + bulk; Channelside tourism adjacency",
      source: { date: "2010", institution: "Port Tampa Bay annual reports", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2022, index: 110, cargoNote: "Modern tonnage + cruise; industrial core south/east of CBD",
      source: { date: "2022", institution: "Port Tampa Bay", url: "https://www.porttb.com/", verificationStatus: "PENDING", accessType: "FREE" } }
  ],

  cigarProduction: [
    { year: 1886, millions: 1, note: "Ybor City founded; Vicente Martinez-Ybor factory opens",
      source: { date: "1886", institution: "Ybor City Museum Society / NPS", url: "https://www.nps.gov/ybor/index.htm", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1895, millions: 50, note: "Rapid factory expansion; immigrant labor corridor",
      source: { date: "1895", institution: "Florida Memory / Ybor histories", url: "https://www.floridamemory.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1900, millions: 100, note: "Tampa emerges as a world cigar capital",
      source: { date: "1900", institution: "NPS Ybor City NHL documentation", url: "https://www.nps.gov/ybor/index.htm", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1920, millions: 500, note: "Peak industrial era; ~10,000+ cigar workers regionally",
      source: { date: "1920", institution: "NPS / local labor histories", url: "https://www.nps.gov/ybor/index.htm", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1929, millions: 450, note: "Mechanization + Depression begin long decline",
      source: { date: "1929", institution: "Ybor City Museum Society", url: "https://www.ybormuseum.org/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1940, millions: 200, note: "Mechanized production; hand-rolled craft shrinks",
      source: { date: "1940", institution: "Florida Memory", url: "https://www.floridamemory.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1960, millions: 50, note: "Industry largely collapsed; urban renewal hits Ybor fabric",
      source: { date: "1960", institution: "NPS / City of Tampa", url: "https://www.nps.gov/ybor/index.htm", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1980, millions: 5, note: "Heritage industry residual; tourism economy rises",
      source: { date: "1980", institution: "Ybor City Development Corporation histories", url: "https://www.yborcityonline.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2000, millions: 2, note: "Boutique / heritage production",
      source: { date: "2000", institution: "Ybor City Museum Society", url: "https://www.ybormuseum.org/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2020, millions: 1, note: "Specialty craft remnant + tourism narrative",
      source: { date: "2020", institution: "Ybor City Museum Society", url: "https://www.ybormuseum.org/", verificationStatus: "PENDING", accessType: "FREE" } }
  ],

  commercialIntensity: [
    { year: 1890, index: 25, note: "Franklin Street retail spine forming",
      source: { date: "1890", institution: "Florida Memory photo surveys", url: "https://www.floridamemory.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1910, index: 55, note: "Banks, hotels, specialty retail densify",
      source: { date: "1910", institution: "Sanborn maps / LOC", url: "https://www.loc.gov/collections/sanborn-maps/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1925, index: 100, note: "Classical downtown peak — department stores, theaters, banks",
      source: { date: "1925", institution: "Tampa Theatre / local commercial histories", url: "https://www.tampatheatre.org/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1940, index: 85, note: "Depression recovery; still the regional retail center",
      source: { date: "1940", institution: "City of Tampa histories", url: "https://www.tampa.gov/info/tampa-history", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1955, index: 70, note: "Auto suburbs and shopping centers siphon retail",
      source: { date: "1955", institution: "Planning literature", url: "https://www.tampa.gov/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1970, index: 40, note: "Urban renewal clearance; vacant lots; retail flight",
      source: { date: "1970", institution: "HUD / City urban renewal records", url: "https://www.tampa.gov/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1980, index: 35, note: "Franklin Street Mall experiment underperforms",
      source: { date: "1980", institution: "Tampa Downtown Partnership history", url: "https://www.tampasdowntown.com/about-us/history/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 1995, index: 50, note: "Convention center, office towers, early entertainment",
      source: { date: "1995", institution: "Tampa Downtown Partnership", url: "https://www.tampasdowntown.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2010, index: 65, note: "Arena, aquarium, museums, condo office mix",
      source: { date: "2010", institution: "Tampa Downtown Partnership", url: "https://www.tampasdowntown.com/", verificationStatus: "PENDING", accessType: "FREE" } },
    { year: 2023, index: 95, note: "Water Street + Riverwalk era mixed-use renaissance",
      source: { date: "2023", institution: "Strategic Property Partners / TDP", url: "https://www.waterstreettampa.com/", verificationStatus: "PENDING", accessType: "FREE" } }
  ],

  developmentCapital: [
    { year: 1891, millions: 3.0, label: "Tampa Bay Hotel (Plant), $2.5M + $0.5M furnishings",
      source: { institution: "Henry B. Plant Museum (University of Tampa), history", date: "1891",
        url: "https://www.plantmuseum.com/about/history",
        note: "'spending $2,500,000 and an additional $500,000 for furnishings'. Opened Feb 5, 1891; west bank, not the CBD.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1927, millions: 1.9, label: "Floridan Hotel, 19 floors",
      source: { institution: "AIA Tampa Bay, Architecture of Tampa Bay tour: Floridan Hotel", date: "1927",
        url: "https://tourtampabayarchitecture.com/page_23-html/",
        note: "'Built at a cost of $1.9 million'; opened 1927. Tampa Theatre (1926, ~$1.2M) is PENDING and not included.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1990, millions: 140, label: "Tampa Convention Center",
      source: { institution: "Tampa Bay Times (St. Petersburg Times archive), 'Convention Center opens in style'", date: "1990-10-20",
        url: "https://www.tampabay.com/archive/1990/10/20/convention-center-opens-in-style/",
        note: "'$140-million building'; a 2000 retrospective cites $156M all-in. Downtown CRA increment serviced the bonds until 2015.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1995, millions: 100, label: "Florida Aquarium (city-backed bonds)",
      source: { institution: "Tampa Bay Times (St. Petersburg Times archive)", date: "2000-02-13",
        url: "https://www.tampabay.com/archive/2000/02/13/former-aquarium-chief-preaches-new-wave-leadership/",
        note: "'$100 million project ... thanks to long-term bonds backed by the city'; opened March 31, 1995.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1996, millions: 160, label: "Ice Palace (now Benchmark International Arena)",
      source: { institution: "Tampa Bay Times (St. Petersburg Times archive)", date: "1996-10-18",
        url: "https://www.tampabay.com/archive/1996/10/18/a-hint-he-owns-the-tampa-bay-lightning/",
        note: "'the $160-million Ice Palace'; the often-repeated $139M figure could not be confirmed institutionally. County-owned; first event Oct 12, 1996.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2000, millions: 110, label: "Tampa Marriott Waterside, 717 rooms",
      source: { institution: "Tampa Bay Times (St. Petersburg Times archive), 'Making room for an inn'", date: "2000-01-10",
        url: "https://www.tampabay.com/archive/2000/01/10/making-room-for-an-inn/",
        note: "$110M hotel beside the Convention Center; city committed $32M in lease payments over 19 years.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2001, millions: 49, label: "Channelside Bay Plaza",
      source: { institution: "Tampa Bay Times", date: "2012-04-20",
        url: "https://www.tampabay.com/news/business/realestate/chicago-groups-4-million-bid-for-tampas-channelside-complex-rejected/1225828/",
        note: "'The $49 million Channelside complex opened in 2001'; Tampa Port Authority owns the land.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2015, millions: 15.6, label: "Riverwalk completion segments (public funding)",
      source: { institution: "Tampa Bay Times", date: "2012-06-20",
        url: "https://www.tampabay.com/news/politics/local/tampa-secures-11-million-federal-grant-to-finish-riverwalk/1236140/",
        note: "DERIVED: $10.9M federal TIGER grant + $4.7M city/THEA for the last two gaps; the Kennedy Blvd overwater section alone cost $9.2M (Times 2015-03-28). Not a total Riverwalk cost.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { year: 2018, millions: 21, label: "Armature Works (Tampa Heights, on the Riverwalk)",
      source: { institution: "Florida Community Loan Fund, borrower profile", date: "2018",
        url: "https://www.fclf.org/meet-our-borrowers-item/armature-works",
        note: "$21M total project; 84,700 sq ft 1910 streetcar barn; opened Feb 2018. Outside the CBD.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2018, millions: 3000, label: "Water Street Tampa, Phase 1 program ($3B private)",
      source: { institution: "Strategic Property Partners, press release (PR Newswire)", date: "2019-07-09",
        url: "https://www.prnewswire.com/news-releases/strategic-property-partners-llc-begins-construction-on-tampas-first-downtown-trophy-office-tower-in-over-25-years-300881900.html",
        note: "'over $3 billion in private investment', 'over 50 acres', 'approximately 9 million square feet'. Later boilerplate (Tampa Bay EDC, 2024) says $3.5B and 74 acres; $4B is unsupported. City and county pledged up to $100M in CRA infrastructure reimbursement (Times 2014-10-08).",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2025, millions: 56.8, label: "West Riverwalk extension (BUILD grant + CRA)",
      source: { institution: "City of Tampa, news release", date: "2025-10-27",
        url: "https://www.tampa.gov/news/2025-10/city-tampa-celebrates-groundbreaking-west-riverwalk-project-175676",
        note: "$56.8M total: $24M federal BUILD, $10M CRA; ~2 miles of the 12.2-mile corridor.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 2025, millions: 1255, label: "Announced 2025–28 program value (Water Street II + cultural anchors)",
      source: { institution: "Strategic Property Partners, Water Street Tampa: What's Next", date: "2025",
        url: "https://www.waterstreettampa.com/whats-next",
        note: "DERIVED sum: Water Street next phase $1.0B + Straz Center $100M + Tampa Museum of Art $110M + Florida Aquarium $45M (TDP 2024-25 Development Guide). Announced, not delivered.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
  ],

  hotelRooms: [
    { year: 1891, rooms: 511, estimate: false,
      note: "Tampa Bay Hotel opens (seasonal resort, west bank).",
      source: { institution: "Henry B. Plant Museum (University of Tampa), history", date: "1891",
        url: "https://www.plantmuseum.com/about/history",
        note: "511 rooms; opened Feb 5, 1891; closed as a hotel 1932; University of Tampa from 1933.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1927, rooms: 827, estimate: true,
      note: "Named land-boom stock: Tampa Bay Hotel 511 + Floridan 316.",
      source: { institution: "AIA Tampa Bay, Architecture of Tampa Bay tour: Floridan Hotel", date: "1927",
        url: "https://tourtampabayarchitecture.com/page_23-html/",
        note: "DERIVED lower bound. Floridan reported as 316 rooms (AIA) or 426 original rooms (Tampa Bay Times 2012). Tampa Terrace (~264, 1925) and Hillsboro Hotel (~400, 1911) are PENDING and excluded.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { year: 2000, rooms: 1238, estimate: true,
      note: "Convention-era anchors: Marriott Waterside 717 + Hyatt Regency 521.",
      source: { institution: "Tampa Bay Times (St. Petersburg Times archive), 'Making room for an inn'", date: "2000-01-10",
        url: "https://www.tampabay.com/archive/2000/01/10/making-room-for-an-inn/",
        note: "DERIVED lower bound from two named hotels; no institutional downtown inventory exists for 1950–2010. Hyatt Regency count from Times 2012-08-23.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { year: 2023, rooms: 3000, estimate: false,
      note: "Walkable convention-package inventory (lower bound).",
      source: { institution: "Visit Tampa Bay, Tampa Convention Center meeting-planner page", date: "2026",
        url: "https://www.visittampabay.com/meeting-planners/convention-center/",
        note: "'more than 3,000 rooms' within walking distance. Water Street added JW Marriott 519 (2020), Hyatt Place/House 345 (2021), EDITION 172 (2022) per HVS 2023-03-07; TDP guide: 167 keys added 2024, 220 under construction, 699 planned.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  landUseShare: [
    { year: 1900, residential: 35, retail: 25, industrial: 20, civic: 10, vacant: 10 },
    { year: 1930, residential: 28, retail: 30, industrial: 18, civic: 12, vacant: 12 },
    { year: 1960, residential: 15, retail: 22, industrial: 15, civic: 18, vacant: 30 },
    { year: 1980, residential: 8, retail: 18, industrial: 10, civic: 22, vacant: 42 },
    { year: 2000, residential: 18, retail: 20, industrial: 5, civic: 25, vacant: 32 },
    { year: 2023, residential: 32, retail: 18, industrial: 3, civic: 22, vacant: 25,
      source: { date: "2023", institution: "City of Tampa GIS / planning generalized model", url: "https://opendata.tampa.gov/", verificationStatus: "PENDING", accessType: "FREE", note: "Generalized core land-use model for narrative; refine with parcel GIS extract." } }
  ],

  /* Hero and footer stats — CONFIRMED sources only (plan §2 rule). */
  heroStats: [
    { value: "200", label: "years from Fort Brooke", sublabel: "1824 – 2024", color: "#fde725",
      source: { institution: "Tampa Bay History Center, Replacing Fort Brooke", date: "2026-09-05",
        url: "https://tampabayhistorycenter.org/exhibit/replacing-fort-brooke/",
        note: "Fort Brooke established January 22, 1824.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "17,366", label: "downtown residents, 2020 Census", sublabel: "up from 8,494 in 2010", color: "#b5de2b",
      source: { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "$3B", label: "Water Street private investment", sublabel: "Strategic Property Partners, 2019", color: "#6ece58",
      source: { institution: "Strategic Property Partners, press release", date: "2019-07-09",
        url: "https://www.prnewswire.com/news-releases/strategic-property-partners-llc-begins-construction-on-tampas-first-downtown-trophy-office-tower-in-over-25-years-300881900.html",
        note: "'over $3 billion in private investment'; later boilerplate says $3.5B.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "384,959", label: "City of Tampa population", sublabel: "2020 U.S. Census", color: "#1f9e89",
      source: { institution: "U.S. Census Bureau, 2020 Census P.L. 94-171 Table P1", date: "2021",
        url: "https://data.census.gov/table/DECENNIALPL2020.P1?g=160XX00US1271000",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  footerStats: [
    { value: "~23,600", label: "Downtown residents, 2025", sublabel: "up from 8,494 in 2010", color: "#1f9e89",
      source: { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "$3B", label: "Modern private capital", sublabel: "Water Street private investment", color: "#35b779",
      source: { institution: "Strategic Property Partners, press release", date: "2019-07-09",
        url: "https://www.prnewswire.com/news-releases/strategic-property-partners-llc-begins-construction-on-tampas-first-downtown-trophy-office-tower-in-over-25-years-300881900.html",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "2.6 mi", label: "Tampa Riverwalk", sublabel: "continuous public waterfront", color: "#6ece58",
      source: { institution: "City of Tampa, Tampa Convention Center news", date: "2020-09-10",
        url: "https://www.tampa.gov/tcc/news/tampa-convention-center-located-along-%E2%80%9Cgreatest-place-america%E2%80%9D%E2%80%94-tampa-riverwalk",
        note: "2.6 miles; APA Great Places in America People's Choice, 2020.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "200 yrs", label: "Arc of this autopsy", sublabel: "1824 – 2024", color: "#b5de2b",
      source: { institution: "Tampa Bay History Center, Replacing Fort Brooke", date: "2026-09-05",
        url: "https://tampabayhistorycenter.org/exhibit/replacing-fort-brooke/",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  mapEvents: [
    { id: "fort-brooke", date: "1824", phase: "fortress", title: "Fort Brooke established", body: "The U.S. Army plants Fort Brooke at the mouth of the Hillsborough River, anchoring the future street grid of downtown Tampa on a military reservation.", lat: 27.9419, lng: -82.4508,
      source: "U.S. Army histories · Florida Memory · City of Tampa" },
    { id: "incorporation", date: "1855", phase: "fortress", title: "Tampa incorporated", body: "Village incorporation (1849) and town status (1855) formalize a tiny commercial settlement beside the fort and river landing.", lat: 27.9475, lng: -82.457,
      source: "City of Tampa · Timeline of Tampa" },
    { id: "plant-rail", date: "1884", phase: "boomtown", title: "Plant System railroad arrives", body: "Henry B. Plant's railroad connects Tampa to the Atlantic Coast Line network, collapsing isolation and unlocking export agriculture, tourism, and industry.", lat: 27.9495, lng: -82.4585,
      source: "Henry B. Plant Museum · Florida Memory" },
    { id: "ybor-founding", date: "1886", phase: "boomtown", title: "Ybor City founded", body: "Vicente Martínez-Ybor founds a planned cigar city east of downtown. Immigrant labor and leaf imports reshape Tampa's economy and street life within a decade.", lat: 27.9606, lng: -82.4414,
      source: "NPS Ybor City · Ybor City Museum Society" },
    { id: "tampa-bay-hotel", date: "1891", phase: "boomtown", title: "Tampa Bay Hotel opens", body: "Plant's Moorish-revival resort hotel on the west bank becomes a Gilded Age landmark and later the University of Tampa campus / Henry B. Plant Museum.", lat: 27.9472, lng: -82.4648,
      source: "Henry B. Plant Museum · University of Tampa" },
    { id: "spanish-american", date: "1898", phase: "boomtown", title: "Spanish–American War embarkation", body: "Tampa becomes a primary embarkation port for U.S. forces bound for Cuba. The waterfront and rail yards surge with temporary military logistics.", lat: 27.9425, lng: -82.448,
      source: "Library of Congress · Florida Memory" },
    { id: "port-phosphate", date: "1915", phase: "metropolis", title: "Phosphate export powerhouse", body: "Channel dredging and phosphate rail links make Port Tampa a global bulk exporter, financing banks, warehouses, and a denser commercial downtown.", lat: 27.932, lng: -82.446,
      source: "Port Tampa Bay · U.S. Army Corps histories" },
    { id: "tampa-theatre", date: "1926", phase: "metropolis", title: "Tampa Theatre opens", body: "An atmospheric movie palace on Franklin Street crowns the 1920s land-boom skyline of banks, department stores, and streetcars.", lat: 27.9489, lng: -82.4595,
      source: "Tampa Theatre · Florida Memory" },
    { id: "land-bust", date: "1929", phase: "depression", title: "Land boom collapse + Depression", body: "Speculative real-estate collapse, bank stress, and the national Depression freeze the skyline. Construction stalls for a generation.", lat: 27.9478, lng: -82.4575,
      source: "Florida Memory · economic histories of the Florida boom/bust" },
    { id: "wwii-shipyard", date: "1942", phase: "depression", title: "WWII industrial surge", body: "Shipbuilding, MacDill Field, and wartime logistics re-industrialize the bayfront and pull labor into the metro — even as the peacetime retail core ages.", lat: 27.9385, lng: -82.445,
      source: "Florida Memory · U.S. military industrial histories" },
    { id: "central-avenue", date: "1955", phase: "suburban", title: "Central Avenue Black business district peak", body: "Central Avenue near downtown is the commercial and cultural spine of Black Tampa — clubs, shops, professional offices — before urban renewal erases most of it.", lat: 27.955, lng: -82.4545,
      source: "USF Special Collections · Florida Memory · local oral histories" },
    { id: "interstate", date: "1963", phase: "renewal", title: "Interstate trenches cut the core", body: "I-4 / I-275 construction carves through neighborhoods east and north of downtown, demolishing housing and severing Ybor, the Scrub, and street-grid continuity.", lat: 27.9525, lng: -82.451,
      source: "FDOT / FHWA urban interstate histories · City of Tampa" },
    { id: "urban-renewal", date: "1967", phase: "renewal", title: "Urban renewal clearance", body: "Federal urban renewal clears large swaths of older housing and small business fabric. Intended modernization leaves long-lived vacant parcels and displaced communities.", lat: 27.951, lng: -82.4555,
      source: "HUD urban renewal program records · local displacement studies" },
    { id: "franklin-mall", date: "1973", phase: "renewal", title: "Franklin Street Mall experiment", body: "Franklin Street is pedestrianized to compete with suburban malls. Without residential density or strong transit, the mall era struggles and is later reopened to cars.", lat: 27.9475, lng: -82.4572,
      source: "Tampa Downtown Partnership history" },
    { id: "convention-center", date: "1990", phase: "revival", title: "Tampa Convention Center opens", body: "A waterfront convention center anchors a new hospitality strategy and signals downtown's pivot from pure office/retail to meetings + tourism.", lat: 27.941, lng: -82.456,
      source: "Tampa Convention Center · City of Tampa" },
    { id: "aquarium", date: "1995", phase: "revival", title: "Florida Aquarium opens", body: "The Florida Aquarium helps rebrand the industrial Channelside into a family tourism node adjacent to the port and future Sparkman Wharf.", lat: 27.9438, lng: -82.4445,
      source: "Florida Aquarium" },
    { id: "arena", date: "1996", phase: "revival", title: "Ice Palace / Amalie Arena", body: "A downtown arena for the Lightning creates nightly activation on the Channelside edge and pairs with cruise and aquarium tourism.", lat: 27.9428, lng: -82.4518,
      source: "Tampa Bay Lightning · City of Tampa" },
    { id: "riverwalk", date: "2010", phase: "waterfront", title: "Riverwalk continuous spine", body: "Decades of segmented riverfront plans coalesce into a continuous pedestrian Riverwalk linking museums, parks, hotels, and the convention district.", lat: 27.9455, lng: -82.459,
      source: "City of Tampa Parks & Recreation · Tampa Riverwalk" },
    { id: "water-street", date: "2018", phase: "waterfront", title: "Water Street Tampa groundbreaking era", body: "Strategic Property Partners launches a 50-plus-acre mixed-use district south of the core — residential towers, offices, hotels, medical school — the largest private redevelopment in modern downtown Tampa.", lat: 27.9425, lng: -82.4535,
      source: "Strategic Property Partners · Water Street Tampa" },
    { id: "sparkman", date: "2018", phase: "waterfront", title: "Sparkman Wharf opens", body: "A shipping-container food hall and lawn on the Channelside waterfront turns former industrial edge into everyday public space.", lat: 27.9442, lng: -82.4475,
      source: "Strategic Property Partners / Armature Works lineage reporting" }
  ],

  scrollSteps: [
    { eventId: "fort-brooke", date: "1824", phase: "fortress", headline: "A fort on a river mouth", narrative: "Downtown Tampa begins as a military reservation. Fort Brooke's parade grounds and wharf logic still haunt the street grid between the Hillsborough River and Hillsborough Bay.", metric_pop: "—", metric_port: "0", metric_note: "Pre-urban military outpost", flyTo: [27.9419, -82.4508], zoom: 15 },
    { eventId: "plant-rail", date: "1884", phase: "boomtown", headline: "The railroad ends isolation", narrative: "Henry Plant's railroad is the single most important infrastructure shock of the 19th century for Tampa. Freight, tourists, and capital arrive on a schedule the river alone could never provide.", metric_pop: "720→5.5k", metric_port: "12", metric_note: "1880–1890 census jump begins", flyTo: [27.9495, -82.4585], zoom: 14 },
    { eventId: "ybor-founding", date: "1886", phase: "boomtown", headline: "Cigar capital next door", narrative: "Ybor City is not downtown, but it is downtown's economic twin. Leaf, labor, mutual-aid societies, and streetcar links fuse the industrial east side to the commercial core.", metric_pop: "5,532", metric_port: "20", metric_note: "Cigar millions rising fast", flyTo: [27.9606, -82.4414], zoom: 14 },
    { eventId: "tampa-bay-hotel", date: "1891", phase: "boomtown", headline: "Gilded Age skyline on the west bank", narrative: "The Tampa Bay Hotel markets Tampa to the world. Minarets become a brand. Tourism and winter society money sit across the river from a still-rough commercial town.", metric_pop: "~6k+", metric_port: "25", metric_note: "500-room destination hotel", flyTo: [27.9472, -82.4648], zoom: 15 },
    { eventId: "spanish-american", date: "1898", phase: "boomtown", headline: "War embarkation boomtown", narrative: "In 1898 Tampa is briefly one of the most important ports in the United States — a staging ground for Cuba. Temporary camps and supply chaos preview the 20th-century logistics city.", metric_pop: "~15k path", metric_port: "40", metric_note: "Military surge capacity", flyTo: [27.9425, -82.448], zoom: 14 },
    { eventId: "port-phosphate", date: "1915", phase: "metropolis", headline: "Phosphate builds banks", narrative: "Bulk exports finance a denser downtown of warehouses, commission houses, and skyscraper banks. The port's gravity is still walking distance from Franklin Street.", metric_pop: "37,782", metric_port: "55", metric_note: "Port index climbing", flyTo: [27.932, -82.446], zoom: 13 },
    { eventId: "tampa-theatre", date: "1926", phase: "metropolis", headline: "Land-boom metropolis", narrative: "Streetcars, department stores, and the Tampa Theatre define a complete downtown. Population crosses 100,000 by 1930. Then the Florida boom breaks.", metric_pop: "101,161", metric_port: "100", metric_note: "Commercial intensity peak", flyTo: [27.9489, -82.4595], zoom: 16 },
    { eventId: "central-avenue", date: "1955", phase: "suburban", headline: "Central Avenue's Black Main Street", narrative: "While white retail begins drifting to automobile suburbs, Central Avenue thrives as Black Tampa's business and nightlife corridor — a parallel downtown soon targeted by clearance.", metric_pop: "124k city", metric_port: "70", metric_note: "Core residents falling", flyTo: [27.955, -82.4545], zoom: 15 },
    { eventId: "interstate", date: "1963", phase: "renewal", headline: "Concrete cuts the grain", narrative: "Interstate trenches are the most violent edit to Tampa's urban form. Neighborhoods are bisected; Ybor is partially amputated; the walkable continuum from downtown to the east side breaks.", metric_pop: "275k*", metric_port: "72", metric_note: "*annexation-inflated city pop", flyTo: [27.9525, -82.451], zoom: 14 },
    { eventId: "urban-renewal", date: "1967", phase: "renewal", headline: "Clearance without replacement", narrative: "Urban renewal demolishes 'blight' faster than it rebuilds community. Vacant land, parking craters, and displaced households become the dominant downtown story for two decades.", metric_pop: "~2.5k DT", metric_port: "74", metric_note: "Downtown residents near trough", flyTo: [27.951, -82.4555], zoom: 15 },
    { eventId: "franklin-mall", date: "1973", phase: "renewal", headline: "A mall without a city", narrative: "Franklin Street Mall tries to copy suburban shopping indoors-outdoors. Missing housing, missing evening population, and weak transit leave the experiment fragile.", metric_pop: "~1.8k DT", metric_port: "75", metric_note: "Commercial intensity trough", flyTo: [27.9475, -82.4572], zoom: 16 },
    { eventId: "convention-center", date: "1990", phase: "revival", headline: "Meetings economy arrives", narrative: "The Convention Center restarts the waterfront as a hospitality machine. Downtown's recovery thesis shifts from department stores to events, offices, and hotels.", metric_pop: "~3.2k DT", metric_port: "85", metric_note: "Hotel rooms rebuild", flyTo: [27.941, -82.456], zoom: 15 },
    { eventId: "arena", date: "1996", phase: "revival", headline: "Sports as urban policy", narrative: "An arena on the Channelside edge creates recurring night-time foot traffic. Paired with the aquarium and cruise terminals, the east waterfront becomes an entertainment district.", metric_pop: "~4k DT", metric_port: "88", metric_note: "Tourism node forms", flyTo: [27.9428, -82.4518], zoom: 15 },
    { eventId: "riverwalk", date: "2010", phase: "waterfront", headline: "The river becomes a street", narrative: "The Riverwalk is infrastructure as narrative: it stitches museums, parks, and hotels into one legible public realm and raises the amenity floor for residential investment.", metric_pop: "~7.8k DT", metric_port: "95", metric_note: "2.6-mile pedestrian spine", flyTo: [27.9455, -82.459], zoom: 14 },
    { eventId: "water-street", date: "2018", phase: "waterfront", headline: "A new district on the bay", narrative: "Water Street Tampa is the post-renewal answer at private scale: streets, towers, hospitality, and a medical school on former surface lots and soft industrial edge — a $3B private bet on 18-hour urbanism.", metric_pop: "12k→15k+", metric_port: "110", metric_note: "Largest modern private CBD bet", flyTo: [27.9425, -82.4535], zoom: 15 }
  ],

  events: [
    { year: 1824, headline: "Fort Brooke founded", yearOffset: 0, body: "Military reservation established at the Hillsborough River mouth — the seed of downtown's street logic." },
    { year: 1855, headline: "Town of Tampa", yearOffset: 31, body: "Municipal government forms around the fort, river landing, and a handful of commercial streets." },
    { year: 1884, headline: "Plant railroad arrives", yearOffset: 60, body: "Rail connection ends geographic isolation and starts the boomtown sequence." },
    { year: 1886, headline: "Ybor City founded", yearOffset: 62, body: "Cigar industrial city established east of the core; immigrant labor transforms the regional economy." },
    { year: 1891, headline: "Tampa Bay Hotel opens", yearOffset: 67, body: "Gilded Age tourism landmark opens on the west bank of the Hillsborough River." },
    { year: 1898, headline: "Spanish–American War port", yearOffset: 74, body: "Embarkation chaos and national attention briefly make Tampa a strategic logistics hub." },
    { year: 1915, headline: "Phosphate export peak path", yearOffset: 91, body: "Port modernization and phosphate rail links finance a denser commercial downtown." },
    { year: 1926, headline: "Land-boom skyline", yearOffset: 102, body: "Tampa Theatre and boom-era commercial architecture mark the classical downtown apex." },
    { year: 1929, headline: "Boom breaks", yearOffset: 105, body: "Florida real-estate collapse and national Depression freeze private construction." },
    { year: 1942, headline: "WWII industrial surge", yearOffset: 118, body: "Shipbuilding and military activity revive employment while the retail core ages." },
    { year: 1955, headline: "Central Avenue apex", yearOffset: 131, body: "Black Main Street thrives even as white retail suburbanizes." },
    { year: 1963, headline: "Interstate construction", yearOffset: 139, body: "I-4/I-275 trenches demolish housing and sever east-side continuity." },
    { year: 1967, headline: "Urban renewal clearance", yearOffset: 143, body: "Federal clearance programs erase blocks faster than they rebuild communities." },
    { year: 1973, headline: "Franklin Street Mall", yearOffset: 149, body: "Pedestrian mall experiment tries to out-mall the suburbs — with limited success." },
    { year: 1990, headline: "Convention Center opens", yearOffset: 166, body: "Waterfront meetings economy becomes the new recovery thesis." },
    { year: 1995, headline: "Florida Aquarium", yearOffset: 171, body: "Channelside tourism node expands beside cruise and port edges." },
    { year: 1996, headline: "Downtown arena", yearOffset: 172, body: "Professional hockey anchors night-time activation on the east waterfront." },
    { year: 2010, headline: "Riverwalk connects", yearOffset: 186, body: "Continuous riverfront walkway raises public-realm quality and residential demand." },
    { year: 2018, headline: "Water Street rises", yearOffset: 194, body: "SPP's multi-billion-dollar district begins transforming the southern CBD edge." },
    { year: 2023, headline: "Dense downtown returns", yearOffset: 199, body: "Residential population, hotels, and mixed-use street life approach a new peak." }
  ],

  sankeyEconomy1925: {
    nodes: [
      { name: "Cigars / tobacco", col: 0, color: "#c0392b" },
      { name: "Phosphate / bulk", col: 0, color: "#d68910" },
      { name: "Rail & steamship", col: 0, color: "#2e86ab" },
      { name: "Retail & services", col: 0, color: "#1e8449" },
      { name: "Tourism / hotels", col: 0, color: "#6c3483" },
      { name: "Port waterfront", col: 1, color: "#c0392b" },
      { name: "Franklin corridor", col: 1, color: "#1e8449" },
      { name: "Ybor industrial", col: 1, color: "#d68910" },
      { name: "West bank hotel", col: 1, color: "#6c3483" },
      { name: "Export earnings", col: 2, color: "#c0392b" },
      { name: "Local wages", col: 2, color: "#2e86ab" },
      { name: "Property rents", col: 2, color: "#1e8449" },
      { name: "Visitor spend", col: 2, color: "#6c3483" }
    ],
    links: [
      { target: 7, value: 28,
        source: 0 },
      { target: 5, value: 8,
        source: 0 },
      { target: 5, value: 22,
        source: 1 },
      { target: 5, value: 12,
        source: 2 },
      { target: 6, value: 6,
        source: 2 },
      { target: 6, value: 18,
        source: 3 },
      { target: 8, value: 10,
        source: 4 },
      { target: 6, value: 4,
        source: 4 },
      { target: 9, value: 30,
        source: 5 },
      { target: 10, value: 12,
        source: 5 },
      { target: 10, value: 22,
        source: 7 },
      { target: 9, value: 6,
        source: 7 },
      { target: 11, value: 16,
        source: 6 },
      { target: 10, value: 12,
        source: 6 },
      { target: 12, value: 10,
        source: 8 },
      { target: 11, value: 4,
        source: 8 }
    ],
    sourceNote: "Synthesized economic-base model from NPS Ybor docs, Port Tampa Bay histories, Florida Memory commercial surveys",
    sourceUrl: "https://www.nps.gov/ybor/index.htm"
  },

  sankeyEconomy2023: {
    nodes: [
      { name: "Finance / office", col: 0, color: "#2e86ab" },
      { name: "Hospitality / events", col: 0, color: "#6c3483" },
      { name: "Residential rents", col: 0, color: "#1e8449" },
      { name: "Healthcare / ed", col: 0, color: "#1f9e89" },
      { name: "Port / logistics", col: 0, color: "#d68910" },
      { name: "Sports / entertainment", col: 0, color: "#c0392b" },
      { name: "CBD office core", col: 1, color: "#2e86ab" },
      { name: "Water Street district", col: 1, color: "#1f9e89" },
      { name: "Channelside / arena", col: 1, color: "#c0392b" },
      { name: "Riverwalk cultural", col: 1, color: "#6c3483" },
      { name: "Port (seaward)", col: 1, color: "#d68910" },
      { name: "Knowledge jobs", col: 2, color: "#2e86ab" },
      { name: "Visitor economy", col: 2, color: "#6c3483" },
      { name: "Resident spend", col: 2, color: "#1e8449" },
      { name: "Tax base / ROI", col: 2, color: "#fde725" }
    ],
    links: [
      { target: 6, value: 22,
        source: 0 },
      { target: 7, value: 10,
        source: 0 },
      { target: 7, value: 12,
        source: 1 },
      { target: 9, value: 8,
        source: 1 },
      { target: 8, value: 6,
        source: 1 },
      { target: 7, value: 14,
        source: 2 },
      { target: 6, value: 6,
        source: 2 },
      { target: 7, value: 12,
        source: 3 },
      { target: 10, value: 14,
        source: 4 },
      { target: 8, value: 12,
        source: 5 },
      { target: 11, value: 18,
        source: 6 },
      { target: 14, value: 10,
        source: 6 },
      { target: 11, value: 14,
        source: 7 },
      { target: 13, value: 16,
        source: 7 },
      { target: 14, value: 12,
        source: 7 },
      { target: 12, value: 14,
        source: 8 },
      { target: 13, value: 4,
        source: 8 },
      { target: 12, value: 8,
        source: 9 },
      { target: 13, value: 6,
        source: 9 },
      { target: 14, value: 10,
        source: 10 },
      { target: 11, value: 4,
        source: 10 }
    ],
    sourceNote: "Synthesized from TDP district mix, SPP Water Street program, Port Tampa Bay modern profile",
    sourceUrl: "https://www.tampasdowntown.com/"
  },

  sankeyLandUse: {
    nodes: [
      { name: "Industrial waterfront", col: 0, color: "#d68910" },
      { name: "Cleared renewal parcels", col: 0, color: "#440154" },
      { name: "Surface parking", col: 0, color: "#3e4989" },
      { name: "Aging retail fabric", col: 0, color: "#26828e" },
      { name: "Historic landmarks", col: 0, color: "#6ece58" },
      { name: "Mixed-use towers", col: 1, color: "#1f9e89" },
      { name: "Cultural / parks", col: 1, color: "#35b779" },
      { name: "Hospitality / arena", col: 1, color: "#b5de2b" },
      { name: "Preserved adaptive reuse", col: 1, color: "#fde725" },
      { name: "Still underused lots", col: 1, color: "#482878" },
      { name: "18-hour downtown", col: 2, color: "#1f9e89" },
      { name: "Event-driven peaks", col: 2, color: "#b5de2b" },
      { name: "Heritage continuity", col: 2, color: "#fde725" },
      { name: "Remaining gaps", col: 2, color: "#482878" }
    ],
    links: [
      { target: 5, value: 14,
        source: 0 },
      { target: 6, value: 8,
        source: 0 },
      { target: 7, value: 10,
        source: 0 },
      { target: 5, value: 12,
        source: 1 },
      { target: 9, value: 10,
        source: 1 },
      { target: 6, value: 6,
        source: 1 },
      { target: 5, value: 16,
        source: 2 },
      { target: 9, value: 8,
        source: 2 },
      { target: 5, value: 8,
        source: 3 },
      { target: 8, value: 6,
        source: 3 },
      { target: 7, value: 4,
        source: 3 },
      { target: 8, value: 12,
        source: 4 },
      { target: 6, value: 4,
        source: 4 },
      { target: 10, value: 40,
        source: 5 },
      { target: 10, value: 12,
        source: 6 },
      { target: 12, value: 6,
        source: 6 },
      { target: 11, value: 14,
        source: 7 },
      { target: 12, value: 14,
        source: 8 },
      { target: 10, value: 4,
        source: 8 },
      { target: 13, value: 18,
        source: 9 }
    ],
    sourceNote: "Conceptual redevelopment pathway model — refine with City of Tampa parcel GIS",
    sourceUrl: "https://opendata.tampa.gov/"
  },

  districtImpact: [
    { district: "Fort Brooke / CBD core", role: "Original civic + commercial spine",
      cost: "Repeated demolition cycles (urban renewal, tax-liability teardowns, parking, office teardowns) erased fine-grain fabric; surviving landmarks are islands in a rebuilt grid.",
      net: "Rebuilt",
      source: [
        { institution: "National Park Service, NRHP nomination: North Franklin Street Historic District (NRIS 02000264)", date: "2002",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NRHP/02000264_text",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Tampa Bay History Center, exhibit: Replacing Fort Brooke", date: "2026-09-05",
        url: "https://tampabayhistorycenter.org/exhibit/replacing-fort-brooke/",
        note: "Fort Brooke established January 22, 1824; the reservation opened to civilian development in 1883.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Franklin Street", role: "Historic Main Street",
      cost: "Suburban-mall-era retail flight (Maas Brothers closed March 1991) and the failed downtown pedestrian mall hollowed storefronts; recovery now rides on residential rooftops (8,494 residents in 2010 to 17,366 in 2020) and a $6M corridor revitalization, not department stores.",
      net: "Recovering",
      source: [
        { institution: "National Park Service, NRHP nomination: North Franklin Street Historic District (NRIS 02000264)", date: "2002",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NRHP/02000264_text",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Tampa Bay History Center, blog: Maas Brothers, of course!", date: "2026-09-05",
        url: "https://tampabayhistorycenter.org/blog/maas-brothers-of-course/",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Tampa Downtown Partnership, 2024-25 Downtown Development Guide", date: "2025-05",
        url: "https://www.tampasdowntown.com/wp-content/uploads/2025/05/Development-Guide-May-2025-DIGITAL.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Central Avenue / The Scrub", role: "Black business & cultural district",
      cost: "Slum clearance demolished the Scrub's homes in 1959 for Central Park Village; 1960s I-4 and urban renewal cut off the 200-plus businesses of Central Avenue, the last of which closed in 1974. Cultural memory persists more than physical fabric.",
      net: "Displaced",
      source: [
        { institution: "City of Tampa, Soulwalk historic marker: The Scrub", date: "2026-09-05",
        url: "https://www.tampa.gov/soulwalk/historic-markers/scrub",
        note: "Black population 4,382 (1900) → 21,551 (1930); 1959 demolition; 1960s I-4 and urban renewal.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa, Public Art at Perry Harvey Sr. Park (History Walk)", date: "2026-09-05",
        url: "https://www.tampa.gov/art-programs/perry-harvey-sr-park",
        note: "200+ Black businesses by 1930; last business closed 1974.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "University of South Florida, Institute on Black Life: Historic Black Neighborhoods of Tampa", date: "2026-09-05",
        url: "https://www.usf.edu/arts-sciences/institutes/black-life/black-life-in-tampa-bay/tampa-neighborhood/historic-black-neighborhoods-tampa.aspx",
        note: "Progress Village built to rehouse families dislocated from the Scrub.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Ybor City", role: "Industrial immigrant city",
      cost: "Interstate 4 split the district and a 1965 urban renewal project leveled 70 acres (660 frame houses, two ethnic clubhouses); the cigar industry's collapse emptied the factories, most of which survive as the core of the National Historic Landmark district. The late-1990s entertainment revival is partial and uneven.",
      net: "Mixed",
      source: [
        { institution: "National Park Service, Ybor City Historic District NHL nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "'70 acres, including 660 frame houses, two ethnic club buildings, a fire station, and a cigarmakers' school were leveled'; 1,349 structures, 956 contributing.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa, Ybor City CRA history", date: "2026-09-05",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "Factories gone by the early 1950s; CRA designated June 2, 1988; revitalized late 1990s.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Channelside / Port edge", role: "Working waterfront → entertainment + residential",
      cost: "Containerized shipping displaced general-cargo work and thousands of longshore jobs by the mid-1970s, leaving docks and warehouses empty; the aquarium, arena and cruise era (1995–) brought event-driven visitor peaks, with a residential neighborhood only filling in after the 2004 CRA.",
      net: "Transformed",
      source: [
        { institution: "City of Tampa, Channel District CRA history", date: "2026-09-05",
        url: "https://www.tampa.gov/CRAs/channel-district/history",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa Community Redevelopment Agency, 2025 Annual Report", date: "2025",
        url: "https://www.tampa.gov/system/files/file-visibility/document/2026/tcra-2025-annual-report-final-ada.pdf",
        note: "Channel District CRA: 221 acres, 2004 base year; taxable value $39.9M (base) → $1.16B (FY25).",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Water Street", role: "Master-planned mixed-use district",
      cost: "High capital intensity and luxury positioning raise inclusion questions even as they restore street life and tax base; the city and county pledged up to $100M in CRA infrastructure reimbursement against $3B of private investment.",
      net: "Catalytic",
      source: [
        { institution: "City of Tampa, Amended and Restated Downtown CRA Plan", date: "2025",
        url: "https://www.tampa.gov/sites/default/files/document/2025/downtown-cra-plan-final.pdf",
        note: "Interpretive synthesis; the plan credits Water Street with delivering the City Center Plan street types.",
        verificationStatus: "DERIVED", accessType: "FREE" },
        { institution: "Tampa Bay Times", date: "2017",
        url: "https://www.tampabay.com/news/business/realestate/A-new-look-at-the-vision-for-Water-Street-Tampa_163282043/",
        note: "'$3 billion project' by Strategic Property Partners.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Tampa Bay Times", date: "2014-10-08",
        url: "https://www.tampabay.com/news/localgovernment/100m-deal-proposed-to-aid-downtown-tampa-redevelopment/2201258/",
        note: "Up to $100M ($50M city + $50M county) CRA reimbursement.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Riverwalk / cultural strip", role: "Public realm connector",
      cost: "Success depends on continuous programming and maintenance; the 2.6-mile trail already reaches Tampa Heights, so the remaining gaps are west (West River extension, $24M USDOT BUILD grant, due December 2026) and east to the Channel District across Beneficial Bridge.",
      net: "Public gain",
      source: [
        { institution: "City of Tampa Community Redevelopment Agency, 2024 Annual Report", date: "2024",
        url: "https://www.tampa.gov/sites/default/files/document/2026/tampacra2024annualreport_ada.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa, news: next step in plan to expand Tampa Riverwalk", date: "2024-04",
        url: "https://www.tampa.gov/news/2024-04/city-tampa-taking-next-step-plan-expand-tampa-riverwalk-115376",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa, Tampa Convention Center news", date: "2020-09-10",
        url: "https://www.tampa.gov/tcc/news/tampa-convention-center-located-along-%E2%80%9Cgreatest-place-america%E2%80%9D%E2%80%94-tampa-riverwalk",
        note: "2.6 miles; APA Great Places in America People's Choice, 2020.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "Harbour Island", role: "Early residential reinvention",
      cost: "A phosphate terminal (Seddon Island, 177 acres) rebuilt as a gated residential community by 1985; its developer-built People Mover to the CBD ran only 1985–1999, and bridge-gated island living still feels separate from downtown street life despite proximity.",
      net: "Stable residential",
      source: [
        { institution: "City of Tampa, Downtown CRA plan (1983 plan and 1988 amendment reproduced in the 2025 plan)", date: "1988",
        url: "https://www.tampa.gov/sites/default/files/document/2025/downtown-cra-plan-final.pdf",
        note: "Harbour Island = Subarea 5; residential from 1985; People Mover 'considered an essential part of the Harbour Island development'.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Tampa Bay Times", date: "2019-01-25",
        url: "https://www.tampabay.com/hillsborough/when-only-their-family-lived-there-young-brothers-found-adventure-on-isolated-harbour-island-20190125/",
        note: "177-acre phosphate terminal → gated community; completed 1985; ~4,300 residents.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "Transportation Research Board, TRID: History of the Tampa Harbour Island People Mover", date: "2018",
        url: "https://trid.trb.org/view/1994625",
        note: "Service June 1985 – January 1999.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
    { district: "West bank (UT / Plant)", role: "Landmark tourism + campus",
      cost: "River-crossing friction historically limited spillover from the 1891 Tampa Bay Hotel (University of Tampa since 1933); Riverwalk, Julian B. Lane Riverfront Park and the West River extension gradually reconnect the bank.",
      net: "Anchor",
      source: [
        { institution: "National Park Service, Tampa Bay Hotel (National Historic Landmark) place page", date: "2026-09-05",
        url: "https://www.nps.gov/places/tampa-bay-hotel.htm",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "National Park Service, NPGallery NRHP record NRIS 72000322", date: "1972-12-05",
        url: "https://npgallery.nps.gov/AssetDetail/NRIS/72000322",
        note: "Listed December 5, 1972; architect J.A. Wood.",
        verificationStatus: "CONFIRMED", accessType: "FREE" },
        { institution: "City of Tampa, Julian B. Lane Riverfront Park", date: "2026-09-05",
        url: "https://www.tampa.gov/parks-and-recreation/featured-parks/riverfrontpark",
        note: "25-acre west-bank park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" }
      ] },
  ],

  disruptionIndex: [
    { district: "CBD retail core", y1950: 10, y1970: 55, y1990: 40, y2020: 25, color: "#1f9e89" },
    { district: "Central Ave / Scrub", y1950: 15, y1970: 95, y1990: 85, y2020: 70, color: "#c0392b" },
    { district: "Ybor residential", y1950: 20, y1970: 80, y1990: 55, y2020: 35, color: "#d68910" },
    { district: "Channelside industrial", y1950: 25, y1970: 40, y1990: 60, y2020: 75, color: "#6c3483" },
    { district: "Waterfront south CBD", y1950: 30, y1970: 50, y1990: 45, y2020: 90, color: "#fde725" }
  ],

  photoArchive: [
    { year: "c. 1900s", title: "Tampa Bay Hotel (Henry B. Plant)", credit: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/Category:Tampa_Bay_Hotel", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/University_of_Tampa%2C_Tampa%2C_Florida.jpg/640px-University_of_Tampa%2C_Tampa%2C_Florida.jpg", caption: "The former Tampa Bay Hotel — now University of Tampa — anchors the west bank skyline." },
    { year: "Historic / NHL district", title: "Ybor City historic streetscape", credit: "NPS Ybor City · Wikimedia Commons", url: "https://www.nps.gov/ybor/index.htm", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Ybor_City_historic_district_streetscape.jpg/640px-Ybor_City_historic_district_streetscape.jpg", caption: "Immigrant cigar city fabric east of downtown — industrial housing and brick factories." },
    { year: "1926 landmark", title: "Tampa Theatre marquee", credit: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/Category:Tampa_Theatre", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Tampa_Theatre_01.jpg/640px-Tampa_Theatre_01.jpg", caption: "Atmospheric movie palace on Franklin Street — surviving land-boom culture infrastructure." },
    { year: "21st century", title: "Downtown Tampa skyline", credit: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/Category:Skylines_of_Tampa,_Florida", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Tampa_Florida_Skyline.jpg/640px-Tampa_Florida_Skyline.jpg", caption: "Post-revival skyline with residential and office towers along the river and bay." },
    { year: "modern waterfront", title: "Harbour Island vantage", credit: "Wikimedia Commons", url: "https://commons.wikimedia.org/wiki/Category:Tampa,_Florida", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tampa_skyline_from_Harbour_Island.jpg/640px-Tampa_skyline_from_Harbour_Island.jpg", caption: "Working bay and skyline — the industrial edge that later hosted Channelside and Water Street." },
    { year: "multi-decade", title: "Florida Memory photographic archive", credit: "State Archives of Florida", url: "https://www.floridamemory.com/discover/photographs/", thumb: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Florida.svg/640px-Flag_of_Florida.svg.png", caption: "Primary open photographic corpus for streets, port labor, cigar factories, and civic events." }
  ],

  eraMilestones: [
    { era: "Fortress\n1824–1883", years: 59, color: "#482878", note: "Military outpost + village" },
    { era: "Boomtown\n1884–1914", years: 30, color: "#3e4989", note: "Rail, cigars, hotel, war port" },
    { era: "Metropolis\n1915–1929", years: 14, color: "#31688e", note: "Phosphate + land boom" },
    { era: "Depression/War\n1929–1945", years: 16, color: "#26828e", note: "Bust then wartime industry" },
    { era: "Suburban\n1945–1962", years: 17, color: "#1f9e89", note: "Auto exodus begins" },
    { era: "Renewal\n1963–1985", years: 22, color: "#fde725", note: "Interstate + clearance" },
    { era: "Revival\n1986–2008", years: 22, color: "#6ece58", note: "Convention/arena/tourism" },
    { era: "Waterfront\n2009–2024", years: 15, color: "#35b779", note: "Riverwalk + Water Street" }
  ]
};

window.crisisData = window.tampaData;
