/**
 * ybor-data.js — window.tampaData for ybor.html.
 *
 * A second study in the same archive. It uses the identical shape as
 * js/data.js so js/app.js can render either without changes: same source
 * objects, same CONFIRMED / PENDING / DERIVED grading, same rule that hero
 * and footer numbers must be CONFIRMED.
 *
 * The eight civic eras are deliberately the SAME vocabulary the downtown
 * study uses. Ybor City has no `fortress` era because it did not exist
 * before 1885, but sharing the spine means the two studies can be read
 * against each other era by era rather than on two private calendars.
 *
 * This is a first evidence pass. Where a figure is widely repeated but not
 * yet traced to the institution that holds it, it is marked PENDING and says
 * so on the page rather than being quietly presented as fact.
 */
window.tampaData = {

  meta: {
    title: "Ybor City: A Company Town That Outlived Its Industry",
    subtitle: "How a cigar manufacturer bought scrubland north-east of Tampa in 1885, what was built on it, who came to work in it, and what the district became",
    span: "1885 - 2024",
    years: 139,
    baseYear: 1885,
    spanYears: 139,
    center: [27.9613, -82.4453],
    defaultZoom: 15,

    studyArea: {
      description: "The Ybor City Historic District and its immediate approaches, north-east of downtown Tampa: the 7th Avenue commercial spine, the surviving cigar factories, the mutual aid society clubhouses and the casita blocks around them.",
      boundingBox: { west: -82.4600, south: 27.9480, east: -82.4250, north: 27.9760 },
      crs: "EPSG:4326 (WGS 84) for stored coordinates; Leaflet renders in EPSG:3857 Web Mercator.",
      geographyNote: "Ybor City is a neighbourhood, not a census place, and its boundaries differ between the National Historic Landmark district, the City of Tampa historic district and the Community Redevelopment Area (133.1 acres). Every figure here records which boundary it counts."
    },

    /* The shared era vocabulary, minus `fortress`: nothing was here to count. */
    eraSlugs: ["boomtown", "metropolis", "depression", "suburban", "renewal", "revival", "waterfront"],

    method: "Every figure carries a source object with an institution, a date, a URL, a verification status and an access type. CONFIRMED means the cited page states the figure. PENDING means the claim is widely published but was not read on the cited institution's own page. DERIVED means the value is an editorial reconstruction whose inputs are named in its note. Hero and footer figures are CONFIRMED only."
  },

  /* ── Era spine ──────────────────────────────────────────────────────────
     Editorial periodization, as on the downtown study. The boundaries are
     this project's; the events inside them are individually cited. */
  eraMilestones: [
    { era: "Boomtown\n1885-1914", years: 30, color: "v2", note: "Founding, factories, immigration",
      source: { institution: "Periodization synthesized from the National Park Service Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "DERIVED. Era boundaries are editorial; the events inside them are individually cited.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Metropolis\n1915-1929", years: 14, color: "v3", note: "Peak output",
      source: { institution: "Periodization synthesized from the National Park Service Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "DERIVED. NPS states Tampa's cigar manufacturing peaked in the 1920s.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Depression\n1929-1945", years: 16, color: "v4", note: "Demand collapse, mechanisation",
      source: { institution: "Periodization synthesized from the National Park Service Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "DERIVED. Era boundaries are editorial.", verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Suburban\n1946-1962", years: 17, color: "v6", note: "The factories close",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "DERIVED boundary. The City states that by the early 1950s the cigar factories were gone.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Renewal\n1963-1985", years: 23, color: "v8", note: "Clearance, then designation",
      source: { institution: "Periodization synthesized from the National Park Service Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "DERIVED. Era boundaries are editorial.", verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Revival\n1986-2008", years: 23, color: "v7", note: "Redevelopment area, entertainment district",
      source: { institution: "City of Tampa, Ybor City Redevelopment Area", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "DERIVED boundary, anchored on the June 1988 CRA designation.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Waterfront\n2009-2024", years: 16, color: "v5", note: "Reinvestment and new development",
      source: { institution: "City of Tampa, Ybor City Redevelopment Area", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city",
        note: "DERIVED. Shares the downtown study's final era label so the two can be read together.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
  ],

  /* ── Hero: CONFIRMED only ───────────────────────────────────────────── */
  heroStats: [
    { value: "1885", label: "land bought north-east of Tampa", sublabel: "40 acres, October 1885", color: "v2",
      source: { institution: "National Park Service, Ybor City Historic District National Historic Landmark nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Land bought October 1885; building from spring 1886.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "1886", label: "first factory in production", sublabel: "Ignacio Haya's, March 1886", color: "v3",
      source: { institution: "National Park Service, Ybor City Historic District National Historic Landmark nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Haya's factory reaches production first, in March 1886.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "9", label: "cigar factories still standing", sublabel: "in the historic district", color: "v7",
      source: { institution: "National Park Service, Ybor City Historic District", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "“Nine key cigar factories survive in the district.”", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "133.1", label: "acres, Ybor City redevelopment area", sublabel: "designated 2 June 1988", color: "v5",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "“On June 2, 1988, Ybor City became a Community Redevelopment Area”, 133.1 acres.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  footerStats: [
    { value: "1887", label: "annexed by Tampa", sublabel: "two years after the land was bought", color: "v2",
      source: { institution: "National Park Service, Ybor City Historic District", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "“Tampa eventually annexed Ybor City in 1887.”", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "1900", label: "cigar capital of the world", sublabel: "the City's own description", color: "v3",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "Became “the cigar capital of the world” by 1900.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "1950s", label: "the cigar factories were gone", sublabel: "by the early 1950s", color: "v8",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "“By the early 1950's the cigar factories were gone.”", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "3", label: "National Historic Landmark districts in Florida", sublabel: "Ybor City is one of them", color: "v7",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "“one of only three National Historic Landmark Districts located in the State of Florida”.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  /* ── Events ─────────────────────────────────────────────────────────── */
  mapEvents: [
    { id: "land-purchase", date: "1885", phase: "boomtown", title: "Forty acres, north-east of town",
      body: "Vicente Martínez-Ybor buys 40 acres of scrubland north-east of Tampa in October 1885, after the Tampa Board of Trade intervenes to keep the deal alive. Construction of a planned cigar town begins the following spring.",
      lat: 27.9613, lng: -82.4453,
      source: { institution: "National Park Service, Ybor City Historic District National Historic Landmark nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Land bought October 1885; building from spring 1886. The Board of Trade's brokering role is widely published but was not read on an institutional page for this pass.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "why-tampa", date: "1885", phase: "boomtown", title: "Why here and not Key West",
      body: "Martínez-Ybor and Ignacio Haya form a partnership in 1885 to develop a cigar-manufacturing town near Tampa. The National Park Service gives the reasons plainly: a warm, humid climate that suited hand-rolling, and closeness to Cuba and its tobacco.",
      lat: 27.9606, lng: -82.4414,
      source: { institution: "National Park Service, Ybor City Historic District", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "“Tampa was an ideal location for Martínez-Ybor's factories because of its warm, humid climate and its close proximity to Cuba.”",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "first-cigar", date: "1886", phase: "boomtown", title: "The first factory reaches production",
      body: "Ignacio Haya's factory is the first in the new town to reach production, in March 1886. Martínez-Ybor's own operation follows as the planned blocks fill in.",
      lat: 27.9613, lng: -82.4453,
      source: { institution: "National Park Service, Ybor City Historic District National Historic Landmark nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Haya's factory reaches production first, March 1886.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "annexation", date: "1887", phase: "boomtown", title: "Tampa annexes Ybor City",
      body: "Two years after the land was bought, the town that had been built beside Tampa becomes part of it. Ybor City keeps its own street grid, its own institutions and its own languages.",
      lat: 27.9625, lng: -82.4400,
      source: { institution: "National Park Service, Ybor City Historic District", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "“Tampa eventually annexed Ybor City in 1887.”", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "marti", date: "1893", phase: "boomtown", title: "Martí on the factory steps",
      body: "José Martí is photographed with cigar workers in Ybor City in 1893, during the years the district's factory floors funded the Cuban independence movement.",
      lat: 27.9606, lng: -82.4414,
      source: { institution: "Wikimedia Commons, public-domain photograph “José Martí in Ybor City”", date: "1893",
        url: "https://commons.wikimedia.org/wiki/File:Jose_Marti_in_Ybor_City.jpg",
        note: "The photograph and its 1893 date are confirmed; the fundraising context is general history and is not sourced to an institution here.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { id: "cigar-capital", date: "1900", phase: "boomtown", title: "Cigar capital of the world",
      body: "By 1900 the City of Tampa's own account has the district as the cigar capital of the world, its factories worked mostly by Cuban cigar makers and, to a lesser degree, by Italians and Spaniards.",
      lat: 27.9620, lng: -82.4430,
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "City's wording: “the cigar capital of the world” by 1900.", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "peak-output", date: "1929", phase: "metropolis", title: "Peak output",
      body: "Cigar manufacturing in Tampa peaks in the 1920s. The figure most often given for Ybor City's best year is roughly 500 million cigars rolled in 1929; it is repeated widely but is not read here on the page of the institution that holds it.",
      lat: 27.9613, lng: -82.4453,
      source: { institution: "National Park Service, Ybor City Historic District", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "NPS CONFIRMS the 1920s peak (“Tampa's cigar manufacturing peaked in the 1920s”). The 500 million figure for 1929 is PENDING and is printed as an approximation, not a measurement.",
        verificationStatus: "PENDING", accessType: "FREE" } },
    { id: "factories-gone", date: "1950", phase: "suburban", title: "The factories close",
      body: "Machine-made cigars, the collapse in demand through the Depression and the shift to cigarettes end hand-rolling as the district's economic base. By the early 1950s the cigar factories are gone.",
      lat: 27.9600, lng: -82.4470,
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "“By the early 1950's the cigar factories were gone.” The causes named here are general history, not the City's wording.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "nhl-district", date: "1990", phase: "renewal", title: "A National Historic Landmark district",
      body: "The district is recognised as a National Historic Landmark, one of only three in Florida. Nine key cigar factories survive inside its boundaries.",
      lat: 27.9630, lng: -82.4420,
      source: { institution: "National Park Service, Ybor City Historic District National Historic Landmark nomination (NHLS 74000641)", date: "1990",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Note the common conflation: the Ybor City Historic District was listed on the National Register in 1974; the National Historic Landmark nomination carries a 1990 date. The two are different designations and are not interchangeable.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "cra", date: "1988", phase: "revival", title: "A redevelopment area",
      body: "On 2 June 1988 Ybor City becomes a Community Redevelopment Area of 133.1 acres, and a redevelopment plan is adopted three weeks later. The core area is later extended twice.",
      lat: 27.9605, lng: -82.4390,
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "CRA 2 June 1988; plan adopted 23 June 1988; extensions agreed March 2003 to 2015 and to 2033.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  scrollSteps: [
    { id: "s1", eventId: "land-purchase", phase: "boomtown", title: "A decision, not a settlement",
      body: "Most neighbourhoods grow outward from something. This one was bought. Forty acres of scrubland north-east of Tampa, in October 1885, by a cigar manufacturer who needed somewhere his trade could work.",
      flyTo: [27.9613, -82.4453], zoom: 15 },
    { id: "s2", eventId: "why-tampa", phase: "boomtown", title: "Why here",
      body: "The reasons were practical. Hand-rolling needs humidity; the leaf came from Cuba; and a railroad had reached Tampa the year before. The National Park Service names the climate and the closeness to Cuba outright.",
      flyTo: [27.9606, -82.4414], zoom: 15 },
    { id: "s3", eventId: "first-cigar", phase: "boomtown", title: "Production, within months",
      body: "Building began in the spring of 1886. Ignacio Haya's factory reached production first, that March.",
      flyTo: [27.9613, -82.4453], zoom: 16 },
    { id: "s4", eventId: "cigar-capital", phase: "boomtown", title: "The cigar capital",
      body: "Within fifteen years the district was, in the City's own words, the cigar capital of the world — its factories worked mostly by Cuban cigar makers, and to a lesser degree by Italians and Spaniards.",
      flyTo: [27.9620, -82.4430], zoom: 15 },
    { id: "s5", eventId: "peak-output", phase: "metropolis", title: "Peak",
      body: "Tampa's cigar manufacturing peaked in the 1920s. What came after was not one shock but several at once: machines, the Depression, and a national switch to cigarettes.",
      flyTo: [27.9613, -82.4453], zoom: 15 },
    { id: "s6", eventId: "factories-gone", phase: "suburban", title: "The industry leaves",
      body: "By the early 1950s the cigar factories were gone. The buildings stayed.",
      flyTo: [27.9600, -82.4470], zoom: 15 },
    { id: "s7", eventId: "nhl-district", phase: "renewal", title: "What was left was worth keeping",
      body: "Nine key cigar factories still stand inside the district, which is now one of only three National Historic Landmark districts in Florida.",
      flyTo: [27.9630, -82.4420], zoom: 15 },
    { id: "s8", eventId: "cra", phase: "revival", title: "A town that outlived its industry",
      body: "In 1988 the district became a 133.1-acre redevelopment area. The company town is gone; the company town's streets, clubhouses and factory shells are still being argued over and built on.",
      flyTo: [27.9605, -82.4390], zoom: 15 },
  ],

  /* ── Media ──────────────────────────────────────────────────────────────
     Reused from the downtown study's media layer, where each of these was
     already rights-checked and its thumbnail confirmed to resolve. Same
     assets, same credit lines, same rights policy. */
  /* ── Media ──────────────────────────────────────────────────────────────
     GENERATED from js/data.js, not retyped. Each of these was already
     rights-checked there and its thumbnail confirmed to resolve; copying
     the records by hand is how you end up inventing a URL or crediting the
     wrong archive. Only the caption is rewritten for this study. */
  mediaAssets: [
    {
      id: "marti-1893",
      era: "boomtown",
      year: "1893",
      title: "José Martí with cigar workers in Ybor City",
      caption: "José Martí with cigar workers in Ybor City, 1893.",
      creator: "unknown (snapshot taken in 1893)",
      license: "Public domain",
      creditLine: "unknown (snapshot taken in 1893) / Public domain photograph, via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jose_Marti_in_Ybor_City.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Jose_Marti_in_Ybor_City.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Jose_Marti_in_Ybor_City.jpg",
      upstreamArchive: "Public domain photograph",
      lat: 27.9606,
      lng: -82.4414,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
    {
      id: "ybor-factory-1902",
      era: "boomtown",
      year: "c. 1902",
      title: "The V. M. Ybor cigar factory",
      caption: "The V. M. Ybor cigar factory around 1902 — the anchor of the planned town.",
      creator: "Unknown",
      license: "Public domain",
      creditLine: "Unknown / Library of Congress, HABS, via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:VIEW_OF_FACTORY_WITH_ADDED_WINGS,_LOOKING_NORTHWEST._TAKEN_CIRCA_1902,_PHOTOGRAPHER_UNKNOWN._-_Ybor_Cigar_Factory,_1916_North_Fourteenth_Street,_Tampa,_Hillsborough_County,_FL_HABS_FLA,29-TAMP,19-32.tif",
      thumbUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/VIEW_OF_FACTORY_WITH_ADDED_WINGS%2C_LOOKING_NORTHWEST._TAKEN_CIRCA_1902%2C_PHOTOGRAPHER_UNKNOWN._-_Ybor_Cigar_Factory%2C_1916_North_Fourteenth_Street%2C_Tampa%2C_Hillsborough_County%2C_FL_HABS_FLA%2C29-TAMP%2C19-32.tif/lossy-page1-960px-thumbnail.tif.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/VIEW_OF_FACTORY_WITH_ADDED_WINGS%2C_LOOKING_NORTHWEST._TAKEN_CIRCA_1902%2C_PHOTOGRAPHER_UNKNOWN._-_Ybor_Cigar_Factory%2C_1916_North_Fourteenth_Street%2C_Tampa%2C_Hillsborough_County%2C_FL_HABS_FLA%2C29-TAMP%2C19-32.tif",
      upstreamArchive: "Library of Congress, HABS",
      lat: 27.962,
      lng: -82.44,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
    {
      id: "hine-cigarmakers-1909",
      era: "boomtown",
      year: "1909",
      title: "Young cigarmakers, photographed by Lewis Hine",
      caption: "Young cigarmakers in a Tampa factory, photographed by Lewis Hine for the National Child Labor Committee in 1909.",
      creator: "Lewis Hine",
      license: "Public domain",
      creditLine: "Library of Congress, National Child Labor Committee (Lewis Hine), via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lewis_Hine,_Cigarmakers,_Tampa,_Florida,_1909.jpg",
      thumbUrl: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Lewis_Hine%2C_Cigarmakers%2C_Tampa%2C_Florida%2C_1909.jpg/960px-Lewis_Hine%2C_Cigarmakers%2C_Tampa%2C_Florida%2C_1909.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Lewis_Hine%2C_Cigarmakers%2C_Tampa%2C_Florida%2C_1909.jpg",
      upstreamArchive: "Library of Congress, National Child Labor Committee (Lewis Hine)",
      upstreamUrl: "https://www.loc.gov/item/2018675065/",
      lat: 27.9606,
      lng: -82.4414,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
    {
      id: "united-cigar-1925",
      era: "metropolis",
      year: "1925",
      title: "A United Cigar Stores storefront",
      caption: "A United Cigar Stores storefront, 1925 — the retail end of the trade the district supplied.",
      creator: "State Library and Archives of Florida",
      license: "Public domain",
      creditLine: "State Library and Archives of Florida / State Archives of Florida, Florida Memory, via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:United_Cigar_Stores_Company-_Tampa,_Florida_(9444920906).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/United_Cigar_Stores_Company-_Tampa%2C_Florida_%289444920906%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/United_Cigar_Stores_Company-_Tampa%2C_Florida_%289444920906%29.jpg",
      upstreamArchive: "State Archives of Florida, Florida Memory",
      upstreamUrl: "https://www.floridamemory.com/items/show/151492",
      lat: 27.9478,
      lng: -82.4578,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
    {
      id: "lector-1929",
      era: "depression",
      year: "1929",
      title: "A lector reading at the Cuesta-Rey cigar factory",
      caption: "A lector reading aloud to cigar rollers at the Cuesta-Rey factory, 1929. The readers were paid by the workers themselves.",
      creator: "Burgert Brothers. Burgert's Studio - Tampa, Florida",
      license: "Public domain",
      creditLine: "Burgert Brothers. Burgert's Studio - Tampa, Florida, via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa,_Florida,_1929.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa%2C_Florida%2C_1929.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa%2C_Florida%2C_1929.jpg",
      upstreamArchive: "Burgert Brothers",
      lat: 27.962,
      lng: -82.44,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
    {
      id: "cigar-makers-1974",
      era: "renewal",
      year: "1974",
      title: "Cuban cigar makers at work in Ybor City",
      caption: "Cuban cigar makers still at work in Ybor City in 1974, long after the large factories had closed.",
      creator: "State Library and Archives of Florida",
      license: "Public domain",
      creditLine: "State Library and Archives of Florida / State Archives of Florida, Florida Memory, via Wikimedia Commons (Public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cuban_cigar_makers_at_work-_Ybor_City,_Florida_(7596637548).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Cuban_cigar_makers_at_work-_Ybor_City%2C_Florida_%287596637548%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Cuban_cigar_makers_at_work-_Ybor_City%2C_Florida_%287596637548%29.jpg",
      upstreamArchive: "State Archives of Florida, Florida Memory",
      lat: 27.9606,
      lng: -82.4414,
      thumbStatus: 200,
      verificationStatus: "CONFIRMED" },
  ],
};
