/**
 * ybor-data.js — window.tampaData for ybor.html.
 *
 * The second study in this archive. Same shape as js/data.js so js/app.js
 * renders either without changes: same source objects, same CONFIRMED /
 * PENDING / DERIVED grading, same rule that hero and footer numbers must be
 * CONFIRMED.
 *
 * GENERATED from a verified research pass, not hand-written: every body,
 * quotation, institution and URL is copied from records whose pages were
 * fetched, and every media record from a set whose direct image URLs were
 * each confirmed to return an image. Retyping is how invented URLs and
 * misattributed archives get in.
 *
 * The era vocabulary is deliberately the downtown study's, minus `fortress`:
 * nothing was here to count before 1885. Sharing the spine lets the two
 * studies be read against each other era by era.
 */
window.tampaData = {

  meta: {
    title: "Ybor City: A Company Town That Outlived Its Industry",
    subtitle: "How a cigar manufacturer contracted with a town of seven hundred people in 1885, what was built on the forty acres he bought, who came to work in it, and what the district became",
    span: "1885 - 2026",
    years: 141,
    baseYear: 1885,
    spanYears: 141,
    center: [27.9612, -82.4443],
    defaultZoom: 15,

    studyArea: {
      description: "The Ybor City Historic District and its approaches: the 7th Avenue commercial spine, the surviving cigar factories, the mutual aid society clubhouses and the blocks around them.",
      boundingBox: { west: -82.4560, south: 27.9540, east: -82.4330, north: 27.9680 },
      crs: "EPSG:4326 (WGS 84) for stored coordinates; Leaflet renders in EPSG:3857 Web Mercator.",
      geographyNote: "Ybor City is a neighbourhood, not a census place. Its boundary differs between the National Historic Landmark district, the City of Tampa historic district and the 133.1-acre Community Redevelopment Area, and most nineteenth-century population figures count the city of Tampa rather than the district. Every figure here records which it counts."
    },

    eraSlugs: ["boomtown", "metropolis", "depression", "suburban", "renewal", "revival", "waterfront"],

    method: "Every figure carries a source object with an institution, a date, a URL, a verification status and an access type. CONFIRMED means the cited page states the figure. PENDING means the claim is published but was not read on the cited institution's own page. DERIVED means an editorial reconstruction whose inputs are named in its note. Hero and footer figures are CONFIRMED only. Where two sources disagree, both are printed and neither is averaged."
  },

  eraMilestones: [
    { era: "Boomtown\n1885-1914", years: 30, color: "v2", note: "Founding, factories, immigration",
      source: { institution: "Periodization synthesized from the NPS Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "DERIVED. Era boundaries are editorial; the events inside them are individually cited.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Metropolis\n1915-1929", years: 15, color: "v3", note: "Peak output, the great clubhouses",
      source: { institution: "Periodization synthesized from the NPS Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "DERIVED. NPS dates the heyday from the 1890s until World War II, with the 1920s the peak decade.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Depression\n1930-1945", years: 16, color: "v4", note: "Cigarettes, machinery, departure",
      source: { institution: "Periodization synthesized from the NPS Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "DERIVED. Era boundaries are editorial.", verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Suburban\n1946-1962", years: 17, color: "v6", note: "The big factories leave",
      source: { institution: "City of Tampa, Ybor City history", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "DERIVED boundary. The City states that by the early 1950s the cigar factories were gone.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Renewal\n1963-1985", years: 23, color: "v8", note: "Clearance, the interstate, then designation",
      source: { institution: "Periodization synthesized from the NPS Ybor City NHL nomination and City of Tampa chronologies", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "DERIVED. Era boundaries are editorial.", verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Revival\n1986-2008", years: 23, color: "v7", note: "Redevelopment area, streetcar",
      source: { institution: "City of Tampa, Ybor City Redevelopment Area", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "DERIVED boundary, anchored on the June 1988 CRA designation.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
    { era: "Waterfront\n2009-2026", years: 17, color: "v5", note: "New development on the western edge",
      source: { institution: "City of Tampa, Ybor City Redevelopment Area", date: "2026-09-13",
        url: "https://www.tampa.gov/CRAs/ybor-city",
        note: "DERIVED. Shares the downtown study's final era label so the two can be read together.",
        verificationStatus: "DERIVED", accessType: "FREE" } },
  ],

  heroStats: [
    { value: "5 Oct 1885", label: "the contract with the Tampa Board of Trade", sublabel: "a town of about 700 people buys an industry", color: "v2",
      source: { institution: "Library of Congress, Business Reference Services — \"Birth of Ybor City, the Cigar Capital of the World\"", date: "2026-09-13",
        url: "https://guides.loc.gov/this-month-in-business-history/october/ybor-city",
        note: "Library of Congress: Ybor \u201ccontracted with the Tampa Board of Trade on October 5, 1885\u201d.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "40", label: "acres bought north-east of Tampa", sublabel: "cleared of underbrush and alligator holes", color: "v3",
      source: { institution: "Library of Congress; National Park Service (NHL nomination and Teaching with Historic Places lesson)", date: "2026-09-13",
        url: "https://guides.loc.gov/this-month-in-business-history/october/ybor-city",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "20,000", label: "employed by the industry at its peak", sublabel: "cigars handcrafted in 36 sizes and shapes", color: "v7",
      source: { institution: "National Park Service", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "NHL nomination: \u201cAt its peak, the industry in Ybor City employed 20,000 persons who handcrafted cigars in 36 sizes and shapes.\u201d The nomination dates the heyday from the 1890s until World War II and does not attach the figure to a single year.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "700 \u2192 6,000", label: "Tampa's population, 1880 to 1890", sublabel: "the decade the cigar town arrived", color: "v5",
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51, \"Ybor City: Cigar Capital of the World\"", date: "2026-09-13",
        url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "Counts the city of Tampa, not the district. Sources disagree on the 1890 figure: 5,500 in the NPS classroom lesson, about 6,000 in the NHL nomination. Both are printed here and neither is averaged.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  footerStats: [
    { value: "Mar 1886", label: "the first cigar", sublabel: "Ignacio Haya's factory got there first", color: "v2",
      source: { institution: "National Park Service (NHL nomination) and Library of Congress", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "176", label: "worker houses built in the first year", sublabel: "plus a streetcar line to Tampa", color: "v6",
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination; NPS Ybor City Historic District page", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "Jun 1887", label: "annexed by Tampa", sublabel: "it kept its separate identity", color: "v7",
      source: { institution: "National Park Service — NHL nomination and Ybor City Historic District page", date: "2026-09-13",
        url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm", verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { value: "6", label: "mutual aid societies founded, 1891-1904", sublabel: "Spanish, Italian, Cuban, Asturian, Afro-Cuban", color: "v8",
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51 \"Ybor City: Cigar Capital of the World\"; Ybor City Historic District NHL/NRHP form", date: "2026-09-13",
        url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "DERIVED count of the societies individually cited in this dataset: El Centro Espanol (1891), L'Unione Italiana (1894), El Club Nacional Cubano / El Circulo Cubano (1899), Los Libres Pensadores Marti-Maceo (1900), Centro Asturiano (1902), La Union Marti-Maceo (1904).",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  /* Tampa's municipal population across the decade the cigar town arrived.
     This counts the CITY, not the district — see meta.studyArea.geographyNote. */
  cityPopulation: [
    { year: 1880, pop: 700, note: "Tampa before the cigar industry.",
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51, \"Ybor City: Cigar Capital of the World\"", date: "2026-09-13",
        url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1887, pop: 3000, note: "Within two years of the first factories.",
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51, \"Ybor City: Cigar Capital of the World\"", date: "2026-09-13",
        url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1890, pop: 5500, estimate: true, note: "Sources disagree: 5,500 (NPS classroom lesson) against about 6,000 (NHL nomination). Both are recorded; neither is averaged.",
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51, \"Ybor City: Cigar Capital of the World\"", date: "2026-09-13",
        url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "The NHL nomination gives about 6,000 for the same year.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  /* Customs duties collected at Tampa: a proxy for the trade the factories
     pulled in, not a measure of cigar output. Labelled as such on the page. */
  portActivity: [
    { year: 1885, index: 683, note: "$683.08 collected in the year before the cigar industry arrived.",
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Dollars of import-export duty collected by Tampa port officials. A proxy for trade volume, NOT cigar output.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1888, index: 83000, note: "$83,000, two years after the factories opened.",
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1896, index: 787000, note: "$787,000.",
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { year: 1900, index: 871000, note: "$871,000 — roughly 1,275 times the 1885 figure.",
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13",
        url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "The multiple is DERIVED arithmetic on the two cited endpoints.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  mapEvents: [
    { id: "board-of-trade", date: "1885", phase: "boomtown", title: "Ybor contracts with the Tampa Board of Trade, 5 October 1885",
      body: "The Library of Congress dates the deal precisely: \"Cigar industrialist Don Vicente Martinez Ybor contracted with the Tampa Board of Trade on October 5, 1885, to relocate his hand rolled cigar manufacturing business Ybor & Co. to what is now known as Ybor City, FL.\" The Board of Trade — Tampa's booster organization — was the counterparty; this is the moment a town of roughly 700 people bought itself an industry.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "Library of Congress, Business Reference Services — \"Birth of Ybor City, the Cigar Capital of the World\"", date: "2026-09-13", url: "https://guides.loc.gov/this-month-in-business-history/october/ybor-city",
        note: "The LoC page states the contract date and the 40 acres but does not state a purchase price, a seller, or the size of any Board of Trade cash inducement. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "forty-acres", date: "1885", phase: "boomtown", title: "Forty acres northeast of Tampa, and the clearing of it",
      body: "\"Ybor purchased 40 acres of land northeast of Tampa, a fishing village, where he moved his cigar industry operations from Key West\" (Library of Congress); the NPS lesson gives the same figure. The NHL nomination picks up the story on the ground: \"Vicente M. Ybor began developing the land he had purchased near Tampa in October 1885. Even before the sale was finalized, he hired Gavino Gutierrez, one of the individuals who had called his attention to Tampa, to plan his factory and housing layout. Workmen felled trees, cleared underbrush, and filled in small lagoons and alligator holes that covered the site.\" Ybor then contracted for a wooden factory and 50 houses.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "Library of Congress; National Park Service (NHL nomination and Teaching with Historic Places lesson)", date: "2026-09-13", url: "https://guides.loc.gov/this-month-in-business-history/october/ybor-city",
        note: "None of the four NPS/LoC pages fetched states the purchase price or names the seller. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "key-west-fire", date: "1886", phase: "boomtown", title: "The Key West fire, and the decision to go all in on Tampa",
      body: "\"Initially, Ybor apparently planned a small-scale development. In early 1886, however, his Key West factory burned, and after he failed in efforts to buy additional land there, he decided to concentrate his energies on Tampa. With the assistance of Eduardo Manrara, additional land was purchased and Gavino Gutierrez was hired to lay out the factory town which became Ybor City.\" Tampa's win over Key West was, on this account, sealed by a fire and a refusal to sell.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "first-cigar", date: "1886", phase: "boomtown", title: "Haya's first cigar, March 1886",
      body: "Ybor and Haya had completed their Ybor City factories shortly before the Key West fire and had begun bringing workers in from Cuba. \"Although both plants had been completed at virtually the same time, Ybor encountered problems with his workers and tobacco supply, which enabled Haya to get into production first, in March 1886.\" The Library of Congress makes the same point about Ignacio Haya, \"an owner of the Sanchez and Haya Co., who technically opened the first cigar factory in Ybor City.\"",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service (NHL nomination) and Library of Congress", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Neither fetched page gives a day-level date for the first Sanchez y Haya cigar. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "the-grid", date: "1886", phase: "boomtown", title: "Gutierrez redraws the plan: from factory lot to full city grid",
      body: "\"During the spring of 1886, Ybor's concept of the project changed, and at his behest Gutierrez drew up a plan for a full-fledged city. Gutierrez utilized a grid pattern based on 200' by 350' blocks with 50' rights-of-way and 10' alleys through the middles of the blocks. Initially, north-south streets were given numerical designations and east-west ones were named for the States. Later, however, numerical designations were used almost entirely.\" That grid is still the bones of Ybor City.",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "The NHL nomination puts the full-city grid in spring 1886; the NPS lesson says Gutierrez \"surveyed an area two miles from Tampa, even drawing up a map to show where streets might run\" already in 1885. The likeliest reading is an initial 1885 sketch and a 1886 town plat, but the fetched documents do not say so explicitly. Placed at Ferlita Bakery, now Ybor City Museum State Park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "land-company", date: "1886", phase: "boomtown", title: "The Ybor Land and Improvement Company, 176 houses and a streetcar",
      body: "\"In October of that year, Ybor and associates organized the Ybor Land and Improvement Company to construct houses and buildings and sell factory sites to other cigar manufacturers, and shortly afterwards Haya started a similar firm. By the end of the year, Ybor alone had constructed 176 worker houses and purchased a streetcar line that connected Ybor City with Tampa.\" By the close of 1886 the Ybor and Haya factories were in full operation between present 6th and 9th Avenues and 12th to 14th Streets, with several hundred worker houses occupied.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination; NPS Ybor City Historic District page", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "annexation", date: "1887", phase: "boomtown", title: "Annexation, June 1887",
      body: "\"The town's rapid growth aroused annexation sentiment in Tampa, and in June 1887, it became legally part of that city, although it maintained its separate identity.\" The NPS district page puts it the same way: \"Tampa eventually annexed Ybor City in 1887, but the Hispanic factory town kept a separate identity.\" Less than two years after the Board of Trade contract, the company town it had bought was inside the city limits.",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "National Park Service — NHL nomination and Ybor City Historic District page", date: "2026-09-13", url: "https://www.nps.gov/places/ybor-city-historic-district-tampa-fl.htm",
        note: "Placed at Ferlita Bakery, now Ybor City Museum State Park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "centro-espanol", date: "1891", phase: "boomtown", title: "El Centro Español founded — the first mutual aid society in Ybor City",
      body: "\"El Centro Espanol, founded in 1891, was the first mutual aid society in Ybor City. To join, applicants had to be either Spaniards by birth or loyal to Spain. Members paid 25 cents a week to enjoy social privileges as well as death and injury benefits.\" The NHL nomination lists it as \"El Centro Espanol 1891\" formed, present building 1912, and calls it \"the first ethnic club of Tampa,\" reflecting \"the trend-setting influence of the founding Spanish-born elite, who long dominated commercial, social, and intellectual life, even though they were less numerous than other immigrant groups.\"",
      lat: 27.9607, lng: -82.4429,
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51 \"Ybor City: Cigar Capital of the World\"; Ybor City Historic District NHL/NRHP form", date: "retrieved 2026-09-13", url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "Placed at El Centro Espanol clubhouse, 1526-1536 E 7th Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "marti-1891", date: "1891", phase: "boomtown", title: "Martí speaks in Ybor City on November 26–27, 1891",
      body: "José Martí delivered two speeches in Ybor City on November 26 and 27, 1891 — \"Con Todos Y Para Todos\" (\"With All and For All\") and \"Los Pinos Nuevos\" (\"The New Growth\") — which, in the National Park Service's words, \"outlined the goals of the United Cuban Revolutionary Party.\" Both speeches were reproduced in newspapers and journals in the United States and Cuba and \"inflamed Cuban desire for independence.\"",
      lat: 27.96179, lng: -82.44516,
      source: { institution: "National Park Service, Teaching with Historic Places — \"Ybor City: Cigar Capital of the World\" (Reading 3)", date: "2026-09-13", url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "The NPS lesson does not name the venue for the two 1891 speeches. Other accounts place them at El Liceo Cubano and date the \"Resolutions of Tampa\" to November 27, 1891 — see the PENDING item on the Liceo Cubano. Placed at El Pasaje / Cherokee Club.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "marti-1893", date: "1893", phase: "boomtown", title: "Martí's 1893 factory-steps speech and the one-day's-pay pledge",
      body: "In 1893 Martí delivered a speech from the cast-iron steps of the 1886 V.M. Ybor cigar factory on 14th Street, urging cigar workers to join the fight against Spanish oppression. The NPS lesson records that \"more than 10,000 Cubans jammed into a small outdoor area in front of the V.M. Ybor Cigar Factory, punctuating Martí's speech with cries of 'Cuba Libre!'\" and that \"following that rousing evening, workers from all the factories pledged to give one day's pay a week to the revolutionary fund.\" From that fund they bought rifles, ammunition and machetes, and hundreds of cigar makers formed infantry companies. The original portico was later taken to Havana and enshrined; the one on the building today is a reproduction.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Register/NHL nomination and NPS Teaching with Historic Places lesson", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "pedrosos", date: "1893", phase: "boomtown", title: "Ruperto and Paulina Pedroso shelter Martí from assassins",
      body: "The Ybor City nomination records that the site of the home of Ruperto and Paulina Pedroso, \"two Black Cubans who sheltered Marti when Spanish assassins were sent to Ybor City in search of him in 1893,\" is now Parque Amigos de José Martí at 1300 E. 8th Avenue. The house burned in the late 1950s; the park was developed in 1960 and is technically Cuban property.",
      lat: 27.96108, lng: -82.44533,
      source: { institution: "National Park Service — Ybor City Historic District nomination (NPGallery)", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Parque Amigos de Jose Marti.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "unione-italiana", date: "1894", phase: "boomtown", title: "Ybor City's Italians — mostly Sicilians — form L'Unione Italiana",
      body: "\"Ybor City's Italians formed L'Unione Italiana in 1894.\" The NHL nomination describes the Italians as \"mostly Sicilians. In many ways culturally similar to the Cubans and Spaniards, partially because Sicily had long been ruled by Spain, they blended easily into the community, with some becoming cigar makers but most engaging in small business and farming.\" The NPS lesson adds that most Italians \"became bilingual in Italian and Spanish\" and that many had \"first come to work in the sugar cane fields in Louisiana.\"",
      lat: 27.9601, lng: -82.43942,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; NPS Teaching with Historic Places lesson 51", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at L'Unione Italiana clubhouse, 1731 E 7th Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "cigar-capital", date: "1900", phase: "boomtown", title: "Tampa becomes the hand-rolled cigar capital of the world",
      body: "\"By 1900 Tampa had become 'the hand-rolled cigar capital of the world.' In addition to Ybor City, another cigar-making community, West Tampa, grew up, and together they supported auxiliary enterprises like box factories and printing plants. The success of the Tampa cigar was largely due to the skilled Latin craftsmen, who took an artistic pride in their work and handcrafted cigars in 36 sizes and shapes.\" The NPS district page states: \"By 1900, Tampa's manufacturers produced the highest-quality hand-rolled cigars in the world, surpassing even Havana, Cuba.\"",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "This is a qualitative rank claim (quality/hand-rolled leadership), not a quantified output ranking. Geographic unit: city of Tampa, including Ybor City and West Tampa. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "circulo-cubano", date: "1899", phase: "boomtown", title: "Cubans form El Club Nacional Cubano, renamed El Círculo Cubano in 1902",
      body: "\"The Cubans formed El Club Nacional Cubano in 1899, which was renamed El Circulo Cubano in 1902.\" The NHL nomination gives a different framing: \"In 1902, the Cuban population of Ybor City organized El Circulo Cubano, choosing this name because the founders sat in a circle when meeting to establish it,\" and lists the club's date formed as 1902. USF Libraries describes the predecessor as \"the Club Nacional Cubano, Octubre 10,\" which served both Black and white Cubans before segregation split it.",
      lat: 27.96188, lng: -82.44432,
      source: { institution: "National Park Service — Teaching with Historic Places lesson 51; Ybor City NHL/NRHP form; USF Libraries Digital Commons", date: "retrieved 2026-09-13", url: "https://www.nps.gov/teachers/classrooms/upload/TWHP-Lessons_51ybor.pdf",
        note: "Sources differ on whether to date the club to 1899 (NPS lesson, as Club Nacional Cubano) or 1902 (NHL nomination, as Círculo Cubano). Both are reported; do not average. Placed at El Circulo Cubano clubhouse, 2010 Avenida Republica de Cuba.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "libres-pensadores", date: "1900", phase: "boomtown", title: "Los Libres Pensadores Martí-Maceo meets for the first time at the Pedroso home",
      body: "USF Libraries states: \"The first official meeting of Los Libres Pensadores ('the freethinkers') take place October 26, 1900 at the home of Cuban immigrants Ruperto and Paulina Pedroso.\" The same source explains the origin in segregation: \"Although the organization originally served both Black and white Cubans as the Club Nacional Cubano, Octubre 10, an era of segregation forced the group to split into two separate societies- the Círculo Cubano and Los Libres Pensadores Martí-Maceo.\" The NHL nomination independently identifies the Pedroso house site as \"the home of Ruperto and Paulina Pedroso, two Black Cubans who sheltered Marti when\" he visited.",
      lat: 27.96108, lng: -82.44533,
      source: { institution: "University of South Florida Libraries — Sociedad la Unión Martí-Maceo Records, Digital Commons @ USF", date: "retrieved 2026-09-13", url: "https://digitalcommons.usf.edu/marti_maceo_records/",
        note: "Placed at Parque Amigos de Jose Marti.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "centro-asturiano", date: "1902", phase: "boomtown", title: "Centro Asturiano formed by immigrants from Asturias",
      body: "The NHL nomination's table of \"the main ethnic clubs of Ybor City\" lists \"Centro Asturiano 1902\" formed, present building 1913. The NPS classroom lesson instead says \"Centro Asturiano, founded in 1904, was named for the province in Spain from which most of its members came.\" The NHL nomination notes Spaniards \"did not begin arriving in large numbers until the 1890s, especially from Asturias and Galicia.\"",
      lat: 27.96202, lng: -82.45084,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; NPS Teaching with Historic Places lesson 51", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Two NPS sources disagree on the founding year: the NHL nomination table says 1902; the NPS Teaching with Historic Places lesson says 1904. Both reported, not reconciled. Placed at Centro Asturiano, 1913 N Nebraska Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "marti-maceo", date: "1904", phase: "boomtown", title: "La Unión Martí-Maceo formed — the Afro-Cuban society excluded from the other clubs",
      body: "The NHL nomination's club table lists \"La Union Marti-Maceo 1904\" formed, with its building dated 1909 (demolished) and 1960. It describes the club as serving \"Ybor City's Afro-Cubans, who were excluded from Ybor City's other Cuban and Spanish clubs,\" and elsewhere notes that Ybor City's Afro-Cubans \"formed a community within this enclave. Segregated by law, they were long excluded, in many ways, from both the Latin and Black communities in Tampa.\" USF Libraries explains the 1904 name: Los Libres Pensadores \"eventually merged with La Unión, an Afro-Cuban society in West Tampa, to form La Sociedad la Unión Martí-Maceo,\" named \"for Cuban heroes Jose Martí and General Antonio Maceo.\"",
      lat: 27.96108, lng: -82.44533,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; USF Libraries Digital Commons", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Parque Amigos de Jose Marti.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "sanatorio", date: "1906", phase: "boomtown", title: "Centro Español's Sanatorio opens — likely the most modern hospital in Florida",
      body: "\"El Centro Espanol, the first ethnic club of Tampa, and Centro Asturiano were the first institutions in Tampa to organize and built major cooperative medical facilities for their memberships, an achievement that presaged modern-day health maintenance organizations. Centro Espanol's Sanatorio, completed in 1906, was probably the most modern and complete hospital in the State at that time. These efforts have been characterized as a response 'to the problems of medical care with a dignity and dedication unequalled in urban America.'\"",
      lat: 27.9607, lng: -82.4429,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP registration form", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at El Centro Espanol clubhouse, 1526-1536 E 7th Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "columbia", date: "1905", phase: "boomtown", title: "Columbia Restaurant",
      body: "NHL nomination entry: \"Columbia Restaurant (2101-2119 E. 7th Avenue). The Columbia Restaurant is Ybor City's most famous and oldest continuously operating eating establishment. Casimirio Hernandez founded it in 1905 as a corner bar and coffee shop, still intact within the restaurant. Later he added a dining room and other facilities.\" The NPS place page for the district likewise calls it \"the oldest continuously operating restaurant in Ybor City.\"",
      lat: 27.96001, lng: -82.43513,
      source: { institution: "National Park Service — NHL/NRHP nomination, Ybor City Historic District", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "The founder's name is spelled 'Casimirio Hernandez' in the nomination; the restaurant's own material spells it Casimiro — I did not fetch a page to adjudicate, so use the nomination spelling only if quoting it. Coordinate PENDING: the address is a range, so I geocoded the midpoint '2117 E 7th Ave, Tampa, FL' via OpenStreetMap Nominatim (queried 2026-09-13), returning a feature named 'Columbia Restaurant' at 27.9600142 / -82.4351326.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "great-fire", date: "1908", phase: "boomtown", title: "Great Ybor City fire; Gonzalez, Fisher and Co. rebuilds",
      body: "The nomination describes the Gonzalez, Fisher, and Co. Cigar Factory (1908-10) as \"built in 1908 by Gonzalez, Fisher, and Co. (1904-10) to replace the factory the firm had lost in the great 1908 fire\" — \"One of the more architecturally elaborate and distinctive cigar factories, representing the middle period of cigar factory construction in Ybor City.\"",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "asturiano-hall", date: "1913", phase: "metropolis", title: "Centro Asturiano opens at 1913 N. Nebraska Street with a 1,062-seat theatre",
      body: "\"Completed in 1913-14 at a prominent spot on the southeast corner of Palm Street and Nebraska Avenue, this 3-story yellow brick and stone structure has a highly decorated facade with Beaux Arts characteristics... Centro Asturiano's most important interior space is its 1062-seat theater, although the 50' onyx bar in the basement lounge, reputedly the longest in the world, is also impressive, and the gymnasium has interesting period features.\" The NPS lesson says the clubhouse \"was unveiled in 1914... built for the then-astronomical cost of $110,000 and touted as 'the most beautiful building in the south' by the Tampa Tribune. It contained a 1,100-seat theater, cantina (bar), library, and ballroom.\" The NHL nomination adds: \"The building has never been vacant. It has been continuously supported by its members.\"",
      lat: 27.96202, lng: -82.45084,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; NPS Teaching with Historic Places lesson 51", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Theatre seat count differs: NHL nomination says 1,062 seats; the NPS lesson says 1,100. Completion given as 1913-14 (NHL) vs 1914 (lesson). Placed at Centro Asturiano, 1913 N Nebraska Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "cuban-club-hall", date: "1917", phase: "metropolis", title: "El Círculo Cubano's Beaux Arts clubhouse completed at 2010 Avenida República de Cuba",
      body: "\"In 1917 the present 4-story, yellow brick, Beaux Arts edifice was completed on the southwest corner of 7th Avenue and 14th Street... A stained glass representation of the Cuban seal is displayed over the main entry.\" The nomination notes \"The cantina and medical clinic still operate.\" The NPS lesson describes the same building as \"completed in 1918, replaced an earlier building damaged by fire. The $60,000 clubhouse contained a cantina, a ballroom decorated by Cuban painters, a theater, pharmacy, library, gymnasium, and boxing arena.\"",
      lat: 27.96188, lng: -82.44432,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; NPS Teaching with Historic Places lesson 51", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Three dates appear in NPS sources for the present Círculo Cubano building: the NHL nomination's narrative says 1917, its own club table says 1907, and the NPS lesson says 1918. Reported as-is; not reconciled. Placed at El Circulo Cubano clubhouse, 2010 Avenida Republica de Cuba.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "italian-club-hall", date: "1918", phase: "metropolis", title: "L'Unione Italiana's clubhouse completed at 1731 E. 7th Avenue",
      body: "\"The club erected the present 3-1/2-story Neoclassical building, which it still occupies, on the southwest corner of 7th Avenue and 18th Street, in 1918... Along its front (north) facade the edifice features four huge Roman Doric columns... The canteen, recreation room, theater, and ballroom are notable rooms.\" The NPS lesson: \"Construction began on the current clubhouse in 1917 after a fire destroyed the previous one. The $80,000 Italian Renaissance-style building, featuring classical columns, terra cotta relief and marble, included a theater, dance floor, library, cantina (bar), and bowling alley.\"",
      lat: 27.9601, lng: -82.43942,
      source: { institution: "National Park Service — Ybor City Historic District NHL/NRHP form; NPS Teaching with Historic Places lesson 51", date: "retrieved 2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "NHL calls the style Neoclassical; the NPS lesson calls it Italian Renaissance-style. Construction start 1917, completion 1918. Placed at L'Unione Italiana clubhouse, 1731 E 7th Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "ferlita", date: "1923", phase: "metropolis", title: "Ferlita Bakery — now Ybor City Museum State Park",
      body: "NHL nomination entry: \"Ferlita Bakery (Ybor City State Museum) (1818 E. 9th Avenue). The bakery was built in 1923 by an Italian immigrant and continued to operate until 1973. It is a 1-story brick building of Mediterranean influenced design that presents an ornate main facade to 9th Avenue. This main facade, of yellow brick, is divided into five bays by six capped pilasters that extend above the massive curved parapet.\" The nomination adds: \"The State acquired the Ferlita Bakery in 1976, restored it, and opened it to the public as the Ybor City State Museum in 1980. The interior was modified to meet museum needs, but the original ovens, one of which dates to the Ferlitas' earlier bakery on the same site, remain in the building.\"",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "National Park Service — NHL/NRHP nomination, Ybor City Historic District", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Coordinate PENDING: geocoded from '1818 E 9th Ave, Tampa, FL 33605' via OpenStreetMap Nominatim (queried 2026-09-13), which returned a matched feature named 'Ybor City Museum' at 27.9619193 / -82.4383459. Not read off a Florida State Parks or NPS page. NOTE a date conflict worth flagging separately: the nomination dates the surviving building to 1923, while Florida State Parks material describes a bakery founded by Francisco Ferlita in 1896 that burned in 1922 and was rebuilt — the two are consistent only if 1923 is the rebuild; I could not fetch floridastateparks.org (HTTP 403) to confirm its wording directly.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "cigarettes", date: "1920s", phase: "metropolis", title: "Cigarette consumption and cigar machinery undercut hand-rolled Ybor",
      body: "The NHL nomination places the origin of the decline inside the boom itself: \"Largely unnoticed due to the demand for good cigars in the prosperous 1920s was the dramatic increase in cigarette consumption. Even more threatening to Ybor City and its economy was the introduction of vastly improved machinery which could produce cigars comparable in workmanship with hand-rolled ones.\" Because buyers believed in the superiority of the handmade article, manufacturers \"had great difficulty in marketing\" machine-made cigars.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "The nomination gives no year for the machinery's introduction — it describes the 1920s as the period of unnoticed threat. Do not attach a specific mechanisation date to this. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "strike-1931", date: "1931", phase: "depression", title: "Major cigarworkers' strike; lectores removed from the factories",
      body: "\"A major strike by cigarworkers in 1931 also contributed to change in Ybor City.\" In its aftermath, according to the nomination, \"The owners brought in many lower-paid native workers and removed the lectores from the factories\" — ending the factory readers who had been the industry's distinctive cultural institution.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "exodus", date: "1940", phase: "depression", title: "Out-migration of the 1930s: a quarter of foreign-born whites, over half of Afro-Cubans leave Tampa",
      body: "\"Between 1930 and 1940, one-quarter of the foreign-born whites, and more than one-half of the Afro-Cubans, left Tampa.\" The National Park Service's public page on the district repeats the figure: \"A quarter of immigrant whites and half of the city's Afro-Cuban population left Tampa between 1930 and 1940.\"",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "National Park Service — NHL nomination and NPS district page", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "This figure is for TAMPA as a whole, not for Ybor City alone. Do not relabel it as an Ybor City population loss. Placed at Ferlita Bakery, now Ybor City Museum State Park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "postwar-paradox", date: "1950", phase: "suburban", title: "Postwar paradox: the industry recovered, the neighbourhood did not",
      body: "\"Although the Tampa cigar industry recovered during World War II and prospered in the immediate postwar era, Ybor City declined. Prosperity enabled many inhabitants to move to other sections of Tampa. By the late 1950s and early 1960s, Ybor City had begun to take on many aspects of an urban slum.\" The City of Tampa's own CRA history compresses this to: \"By the early 1950's the cigar factories were gone.\"",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service NHL nomination; City of Tampa CRA history", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "THE TWO SOURCES DISAGREE. The NPS nomination says the cigar industry recovered in WWII and prospered into the immediate postwar era, and it documents cigar firms occupying Ybor factories into the 1960s and 1970s. The City of Tampa says the factories \"were gone\" by the early 1950s. Report both; do not reconcile or average. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "american-cigar", date: "1954", phase: "suburban", title: "American Cigar Company leaves the Ybor Factory Complex after 53 years",
      body: "The nomination's building inventory dates the tenancies of the original Ybor factory complex at 1910–1916 Avenida Republica de Cuba / 14th Street: Ybor-Manrara Cigar Factory 1886–99, American Cigar Company 1901–54, and Hava-A-Tampa 1955–72.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "These are occupancy date ranges from the inventory, not stated closure dates. A range ending is evidence the firm left the building, not necessarily that the firm failed. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "urban-renewal", date: "1965", phase: "renewal", title: "Urban renewal levels 70 acres of Ybor City; Interstate 4 splits the community",
      body: "\"In 1965 Ybor City became the target of a major urban renewal project. During the next few years, 70 acres, including 660 frame houses, two ethnic club buildings, a fire station, and a cigarmakers' school were leveled. Although plans for redevelopment were announced, they largely came to naught because expected Federal urban renewal money did not materialize. The construction of Interstate 4 also split the community.\" The nomination adds that the renewal project \"sparked a revival of interest in the area among the Latin community to preserve its culture and most significant buildings.\"",
      lat: 27.96108, lng: -82.44533,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "Placed at Parque Amigos de Jose Marti.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "national-register", date: "1974", phase: "renewal", title: "Ybor City Historic District listed in the National Register of Historic Places",
      body: "The later NHL nomination describes the earlier designation as the \"National Register Historic District, listed in 1974, which includes mainly the 7th Avenue commercial corridor and adjoining cigar factories\" — and notes the NHL boundary adds \"residential components to the south and northeast of the 7th Avenue strip.\" The NPS reference number for the district is 74000641, consistent with a 1974 listing. THIS IS A DIFFERENT DESIGNATION, AND A DIFFERENT DATE, FROM THE NATIONAL HISTORIC LANDMARK.",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "National Park Service — Ybor City Historic District National Historic Landmark nomination", date: "2026-09-13", url: "https://npgallery.nps.gov/NRHP/GetAsset/NHLS/74000641_text",
        note: "The YEAR 1974 is confirmed by the NPS document I read. The commonly cited exact day, August 28, 1974, is NOT confirmed — I did not read it on an NPS page in this session. Treat the day as PENDING. Placed at Ferlita Bakery, now Ybor City Museum State Park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "cra", date: "1988", phase: "revival", title: "Ybor City becomes a Community Redevelopment Area",
      body: "\"On June 2, 1988, Ybor City became a Community Redevelopment Area (CRA)\" under Florida Statutes Chapter 163, covering 133.1 acres. A redevelopment plan prepared in May 1988 aimed to eliminate conditions of blight and create conditions for continued private reinvestment. City Council then adopted an ordinance establishing the Redevelopment Trust Fund — the tax increment district — for the area.",
      lat: 27.96192, lng: -82.43835,
      source: { institution: "City of Tampa — Ybor City CRA history", date: "2026-09-13", url: "https://www.tampa.gov/CRAs/ybor-city/history",
        note: "The 133.1-acre figure and the June 2, 1988 date are both from the City of Tampa page. The stated CRA boundaries (CSX line south, 22nd Street east, Nebraska Avenue west, I-4 north) appeared in search results and are PENDING. Placed at Ferlita Bakery, now Ybor City Museum State Park.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "streetcar", date: "2002", phase: "revival", title: "TECO Line Streetcar reconnects Ybor City to downtown Tampa",
      body: "The City of Tampa states: \"The first 2.4-mile-long segment opened for service in 2002 while a 0.3-mile-long extension opened for service in December 2010.\" The result is \"a 2.7 mile long fixed guideway transit system\" that \"connects downtown Tampa, with the Channelside District and Ybor City Historic District.\" The line restores a rail link of the kind Vicente Ybor himself created — the NHL nomination records that by the end of 1886 Ybor had \"purchased a streetcar line that connected Ybor City with Tampa.\"",
      lat: 27.96001, lng: -82.43513,
      source: { institution: "City of Tampa — Mobility Department", date: "2026-09-13", url: "https://www.tampa.gov/mobility/transportation/streetcar",
        note: "The City page gives the YEAR 2002 only. The commonly cited opening day of October 19, 2002 is PENDING — it came from search snippets, not a page I read. Placed at Columbia Restaurant, 2117 E 7th Avenue.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
    { id: "gasworx", date: "2026", phase: "waterfront", title: "Gasworx: a six-million-square-foot development on Ybor City's western edge",
      body: "The developer's own site describes Gasworx as \"a six-million-square-foot mixed-use development\" and \"Tampa's newest neighborhood, built to honor its oldest, Ybor City,\" adjacent to \"a National Historic Landmark District adjacent to downtown Tampa.\" KETTLER is identified as the developer, with James Nozar as President of Development. Phase One components listed on the site — including The Stevedore, La Unión and The Park — total roughly 1,223 residential units, about 197,500 square feet of retail and 108,000 square feet of office.",
      lat: 27.96117, lng: -82.44433,
      source: { institution: "Gasworx (KETTLER)", date: "2026-09-13", url: "https://gasworx.com/",
        note: "THE ACREAGE IS NOT CONFIRMED. The widely repeated \"50 acres\" figure, and Darryl Shaw's role as land assembler and joint-venture partner, appeared only in search snippets from trade press — PENDING, not verified here. The developer site stated no acreage, no boundaries and no construction timeline. Figures are Phase One sums computed from the site's project listings, not a total for the development. Placed at Ybor Factory Complex, the Ybor-Manrara factory at 9th Avenue and 14th Street.",
        verificationStatus: "CONFIRMED", accessType: "FREE" } },
  ],

  scrollSteps: [
    { eventId: "board-of-trade", date: "1885", phase: "boomtown",
      headline: "A town buys itself an industry",
      narrative: "Most neighbourhoods grow. This one was contracted for. On 5 October 1885 a cigar manufacturer worn down by labour conflict in Key West signed a deal with the booster club of a Florida town of about seven hundred people.",
      metric_pop: "700", metric_port: "$683", metric_note: "Tampa, 1880 census · customs duty collected, 1885",
      media: ["jos-mart-in-ybor-city-9"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "forty-acres", date: "1885", phase: "boomtown",
      headline: "Forty acres of scrub",
      narrative: "Workmen felled trees, cleared underbrush and filled in lagoons and alligator holes. Before the sale had even closed, Gavino Gutierrez was hired to lay out where the factory and the houses would go.",
      metric_pop: "700", metric_port: "$683", metric_note: "Tampa, 1880 census",
      media: ["sanborn-fire-insurance-map-from-tampa-hi-21"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "first-cigar", date: "1886", phase: "boomtown",
      headline: "March 1886",
      narrative: "Both factories finished at almost the same moment, but Ybor hit trouble with workers and tobacco, so Ignacio Haya got into production first.",
      metric_pop: "3,000", metric_port: "—", metric_note: "Tampa, 1887 · over 3,000 had arrived by the end of 1886",
      media: ["interior-of-cigar-factory-tampa-fla-post-22"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "the-grid", date: "1886", phase: "boomtown",
      headline: "From factory lot to city",
      narrative: "That spring the plan changed. Gutierrez drew a full city on a grid of 200-by-350-foot blocks with ten-foot alleys through the middles. Those bones are still there.",
      metric_pop: "3,000", metric_port: "—", metric_note: "Tampa, 1887",
      media: ["streetcar-and-buildings-in-ybor-city-flo-7"],
      flyTo: [27.96192, -82.43835], zoom: 16 },
    { eventId: "annexation", date: "1887", phase: "boomtown",
      headline: "Absorbed, but not dissolved",
      narrative: "Tampa annexed the town in June 1887. It kept its own languages, its own institutions and its own idea of itself.",
      metric_pop: "3,000", metric_port: "$83,000", metric_note: "Tampa, 1887 · duty collected, 1888",
      flyTo: [27.96192, -82.43835], zoom: 16 },
    { eventId: "centro-espanol", date: "1891", phase: "boomtown",
      headline: "What the workers built for themselves",
      narrative: "From 1891 the immigrant communities founded mutual aid societies that sold prepaid medical care and built clubhouses, theatres and hospitals of their own.",
      metric_pop: "5,500", metric_port: "—", metric_note: "Tampa, 1890 — the NHL nomination says about 6,000 for the same year",
      media: ["centro-espa-ol-de-tampa-ybor-city-florid-10"],
      flyTo: [27.9607, -82.4429], zoom: 16 },
    { eventId: "marti-1893", date: "1893", phase: "boomtown",
      headline: "A revolution funded from the factory floor",
      narrative: "Jose Marti came repeatedly to Ybor City, and the cigar workers pledged a day’s pay to the Cuban cause.",
      metric_pop: "5,500", metric_port: "—", metric_note: "Tampa, 1890",
      media: ["jos-mart-with-cigar-workers-of-the-vicen-8","jos-mart-in-ybor-city-9"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "cigar-capital", date: "1900", phase: "boomtown",
      headline: "The cigar capital of the world",
      narrative: "By 1900 the district was the centre of hand-rolled cigar manufacture. At its peak the industry here employed twenty thousand people, making cigars in thirty-six sizes and shapes.",
      metric_pop: "—", metric_port: "$871,000", metric_note: "Duty collected, 1900 — roughly 1,275 times the 1885 figure",
      media: ["interior-of-a-large-cigar-factory-with-l-6"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "cigarettes", date: "1920s", phase: "metropolis",
      headline: "Machines, and a cheaper habit",
      narrative: "Cigarette consumption and cigar machinery undercut hand-rolling. What followed was not one shock but several at once.",
      metric_pop: "—", metric_port: "—", metric_note: "No sourced Ybor City output series exists; none is invented here",
      media: ["lector-reading-at-the-cuesta-rey-cigar-c-11"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "strike-1931", date: "1931", phase: "depression",
      headline: "The readers are removed",
      narrative: "The 1931 strike ended the lector, the reader whom the rollers themselves had paid to read news and novels aloud across the factory floor.",
      metric_pop: "—", metric_port: "—", metric_note: "The lector system ends",
      media: ["interior-view-of-cigar-factory-ybor-city-12"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
    { eventId: "exodus", date: "1930s", phase: "depression",
      headline: "The people leave",
      narrative: "Through the 1930s a quarter of the foreign-born white population left, and the district began emptying out.",
      metric_pop: "—", metric_port: "—", metric_note: "Out-migration through the decade",
      media: ["centro-espanol-entrance-spanish-casino-s-23"],
      flyTo: [27.96192, -82.43835], zoom: 16 },
    { eventId: "urban-renewal", date: "1965", phase: "renewal",
      headline: "Cleared, and cut",
      narrative: "Urban renewal levelled acreage in the 1960s and Interstate 4 was driven through the district.",
      metric_pop: "—", metric_port: "—",
      flyTo: [27.96108, -82.44533], zoom: 16 },
    { eventId: "national-register", date: "1974", phase: "renewal",
      headline: "What was left was worth keeping",
      narrative: "The district was listed on the National Register in 1974 and was later designated a National Historic Landmark District, one of only three in Florida.",
      metric_pop: "—", metric_port: "—",
      media: ["cuban-cigar-makers-at-work-ybor-city-flo-14"],
      flyTo: [27.96192, -82.43835], zoom: 16 },
    { eventId: "streetcar", date: "2002", phase: "revival",
      headline: "Reconnected",
      narrative: "In 2002 a streetcar line reconnected Ybor City to downtown Tampa, a century after Ybor bought the first one.",
      metric_pop: "—", metric_port: "—",
      media: ["c-rculo-cubano-de-tampa-the-cuban-club-15","ybor-square-the-former-ybor-cigar-factor-16"],
      flyTo: [27.96001, -82.43513], zoom: 16 },
    { eventId: "gasworx", date: "2026", phase: "waterfront",
      headline: "Still being built on",
      narrative: "The company town is gone. Its streets, clubhouses and factory shells are still being argued over and developed.",
      metric_pop: "—", metric_port: "—",
      media: ["east-7th-avenue-ybor-city-19","j-c-newman-cigar-co-building-ybor-city-20"],
      flyTo: [27.96117, -82.44433], zoom: 16 },
  ],

  mediaAssets: [
    { id: "a-rarniriz-cigar-co-tampa-fla-tampa-fla--0", era: "boomtown", year: "1909 (January)",
      title: "A Rarniriz Cigar Co., Tampa, Fla. Tampa, Fla. Location: Tampa, Florida.",
      caption: "Hine's NCLC survey of Tampa cigar factories, January 1909. Title as catalogued by LOC, including the misspelling of Ramirez.",
      creator: "Lewis Wickes Hine", license: "Public domain — LOC rights advisory: \"No known restrictions on publication.\"",
      creditLine: "Hine, Lewis Wickes, 1874-1940, photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA — National Child Labor Committee (Lewis Hine photographs)",
      sourceUrl: "https://www.loc.gov/item/2018675069/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04518v.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04518v.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "salvador-rodrignez-i-e-rodriguez-cigar-c-1", era: "boomtown", year: "1909 (January)",
      title: "Salvador Rodrignez [i.e., Rodriguez?] Cigar Co., Tampa, Fla. Location: Tampa, Florida.",
      caption: "LOC's catalogued title preserves Hine's own misspelling of the Rodriguez firm.",
      creator: "Lewis Wickes Hine", license: "Public domain — LOC rights advisory: \"No known restrictions on publication.\"",
      creditLine: "Hine, Lewis Wickes, 1874-1940, photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA — National Child Labor Committee (Lewis Hine photographs)",
      sourceUrl: "https://www.loc.gov/item/2018675067/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04516v.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04516v.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "one-of-the-strippers-in-tampa-fla-cigar--2", era: "boomtown", year: "1909 (January)",
      title: "One of the strippers in Tampa, Fla., Cigar factory. Location: Tampa, Florida.",
      caption: "A \"stripper\" — the worker who stripped the stem from the tobacco leaf before rolling.",
      creator: "Lewis Wickes Hine", license: "Public domain — LOC rights advisory: \"No known restrictions on publication.\"",
      creditLine: "Hine, Lewis Wickes, 1874-1940, photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA — National Child Labor Committee (Lewis Hine photographs)",
      sourceUrl: "https://www.loc.gov/item/2018675073/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04522v.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04522v.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "some-of-the-cigarmakers-f-sierra-co-tamp-3", era: "boomtown", year: "1909 (January)",
      title: "Some of the cigarmakers F. Sierra Co. Tampa, Fla. Location: Tampa, Florida.",
      caption: "Cigarmakers posed outside the F. Sierra Co. factory.",
      creator: "Lewis Wickes Hine", license: "Public domain — LOC rights advisory: \"No known restrictions on publication.\"",
      creditLine: "Hine, Lewis Wickes, 1874-1940, photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA — National Child Labor Committee (Lewis Hine photographs)",
      sourceUrl: "https://www.loc.gov/item/2018675066/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04515v.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04515v.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "cigarmakers-in-factory-of-filogamo-alvar-4", era: "boomtown", year: "1909 (January)",
      title: "Cigarmakers in factory of Filogamo & Alvarez, Tampa, Fla. Work was slack. Location: Tampa, Florida.",
      caption: "Hine repeatedly noted that work was \"slack\" during his January 1909 Tampa visit.",
      creator: "Lewis Wickes Hine", license: "Public domain — LOC rights advisory: \"No known restrictions on publication.\"",
      creditLine: "Hine, Lewis Wickes, 1874-1940, photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA — National Child Labor Committee (Lewis Hine photographs)",
      sourceUrl: "https://www.loc.gov/item/2018675065/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04514v.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/nclc/04500/04514v.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (National Child Labor Committee Collection)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "ybor-cigar-factory-1916-north-fourteenth-5", era: "renewal", year: "undated (LOC: \"Documentation compiled after 1933\")",
      title: "Ybor Cigar Factory, 1916 North Fourteenth Street, Tampa, Hillsborough County, FL",
      caption: "HABS colour transparency of the V. M. Ybor cigar factory. Era assignment is uncertain — see notes.",
      creator: "Historic American Buildings Survey / Walter Smalling, Jr.", license: "Public domain (U.S. Government work) — LOC rights advisory: \"No known restrictions on images made by the U.S. Government; images copied from other sources may be restricted.\"",
      creditLine: "Historic American Buildings Survey, creator; Walter Smalling, Jr., photographer. Library of Congress Prints and Photographs Division Washington, D.C. 20540 USA",
      sourceUrl: "https://www.loc.gov/item/fl0120/",
      thumbUrl: "https://tile.loc.gov/storage-services/service/pnp/habshaer/fl/fl0100/fl0120/color/571145cv.jpg",
      fullUrl: "https://tile.loc.gov/storage-services/service/pnp/habshaer/fl/fl0100/fl0120/color/571145cv.jpg",
      upstreamArchive: "Library of Congress, Prints & Photographs Division (Historic American Buildings Survey)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "interior-of-a-large-cigar-factory-with-l-6", era: "boomtown", year: "circa 1900",
      title: "Interior of a large cigar factory with lector, Tampa, Florida",
      caption: "Rows of cigar rollers at their benches with the lector's platform visible at right.",
      creator: "Unknown", license: "Public domain",
      creditLine: "Unknown photographer / State Archives of Florida, Florida Memory (item 141689), via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Interior_of_a_large_cigar_factory_with_lector_Tampa,_Florida.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Interior_of_a_large_cigar_factory_with_lector_Tampa%2C_Florida.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Interior_of_a_large_cigar_factory_with_lector_Tampa%2C_Florida.jpg",
      upstreamArchive: "State Archives of Florida / Florida Memory, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "streetcar-and-buildings-in-ybor-city-flo-7", era: "boomtown", year: "circa 1900",
      title: "Streetcar and buildings in Ybor City, Florida",
      caption: "An Ybor City streetscape with a streetcar; Florida Memory dates the print ca. 1900.",
      creator: "Unknown", license: "Public domain",
      creditLine: "Florida Memory / State Archives of Florida, local call number FPS1506, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Streetcar_and_buildings_in_Ybor_City,_Florida_(10926367793).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Streetcar_and_buildings_in_Ybor_City%2C_Florida_%2810926367793%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Streetcar_and_buildings_in_Ybor_City%2C_Florida_%2810926367793%29.jpg",
      upstreamArchive: "State Archives of Florida / Florida Memory, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "jos-mart-with-cigar-workers-of-the-vicen-8", era: "boomtown", year: "1893",
      title: "José Martí with cigar workers of the Vicente Martínez Ybor factory, Tampa",
      caption: "Martí with tabaqueros at the Vicente Martínez Ybor factory; the Commons file also names Serafín Sánchez, José Dolores Poyo, Esteban Candan and Eligio Carbonell, and says it was published in Cuba y América (Havana, 20 July 1900).",
      creator: "José María Aguirre", license: "CC0",
      creditLine: "Photograph by José María Aguirre; Cuba, Secretaría de Instrucción Pública y Bellas Artes, \"Iconografía del Apóstol Martí,\" via Wikimedia Commons (CC0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jos%C3%A9_Mart%C3%AD_junto_a_tabaqueros_de_la_f%C3%A1brica_de_Vicente_Mart%C3%ADnez_Ibor_en_Tampa,_Estados_Unidos_1893.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Jos%C3%A9_Mart%C3%AD_junto_a_tabaqueros_de_la_f%C3%A1brica_de_Vicente_Mart%C3%ADnez_Ibor_en_Tampa%2C_Estados_Unidos_1893.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Jos%C3%A9_Mart%C3%AD_junto_a_tabaqueros_de_la_f%C3%A1brica_de_Vicente_Mart%C3%ADnez_Ibor_en_Tampa%2C_Estados_Unidos_1893.jpg",
      upstreamArchive: "Wikimedia Commons (from Iconografía del Apóstol Martí)",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "jos-mart-in-ybor-city-9", era: "boomtown", year: "1893",
      title: "José Martí in Ybor City",
      caption: "Commons description: Cuban patriot José Martí poses with cigar factory workers after giving a speech in Ybor City, Tampa, in 1893.",
      creator: "Unknown", license: "Public domain",
      creditLine: "Unknown photographer / University of South Florida historical photography collections, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Jose_Marti_in_Ybor_City.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Jose_Marti_in_Ybor_City.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Jose_Marti_in_Ybor_City.jpg",
      upstreamArchive: "University of South Florida historical photography collections, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "centro-espa-ol-de-tampa-ybor-city-florid-10", era: "boomtown", year: "circa 1914",
      title: "Centro Español de Tampa, Ybor City, Florida",
      caption: "The Centro Español de Tampa clubhouse; the Florida Memory note says the building was completed in 1912 and served Spanish and Cuban immigrants of the cigar districts.",
      creator: "Unknown", license: "Public domain",
      creditLine: "Florida Memory / State Archives of Florida, local call number PR12438, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Centro_Espa%C3%B1ol_de_Tampa-_Ybor_City,_Florida_(7255516812).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Centro_Espa%C3%B1ol_de_Tampa-_Ybor_City%2C_Florida_%287255516812%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Centro_Espa%C3%B1ol_de_Tampa-_Ybor_City%2C_Florida_%287255516812%29.jpg",
      upstreamArchive: "State Archives of Florida / Florida Memory, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "lector-reading-at-the-cuesta-rey-cigar-c-11", era: "metropolis", year: "1929",
      title: "Lector reading at the Cuesta-Rey Cigar Company, Tampa, Florida",
      caption: "Interior of the Cuesta-Rey factory with the lector reading from his raised platform at the right.",
      creator: "Burgert Brothers", license: "Public domain",
      creditLine: "Burgert Brothers (Burgert's Studio, Tampa) / Florida Department of State, Division of Library and Information Services — Florida Memory item 27163, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa,_Florida,_1929.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa%2C_Florida%2C_1929.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Lector_reading_at_Cuesta-Rey_Cigar_Company_-_Tampa%2C_Florida%2C_1929.jpg",
      upstreamArchive: "State Archives of Florida / Florida Memory, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "interior-view-of-cigar-factory-ybor-city-12", era: "depression", year: "circa 1930–1945",
      title: "Interior view of cigar factory, Ybor City (linen postcard)",
      caption: "A colour linen-texture postcard of an Ybor City cigar factory floor, 3.5 × 5.5 in.",
      creator: "Tichnor Brothers", license: "CC BY-SA 4.0",
      creditLine: "The Tichnor Brothers Collection, Boston Public Library, Print Department, via Wikimedia Commons (CC BY-SA 4.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Interior_view_of_cigar_factory,_Ybor_City.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Interior_view_of_cigar_factory%2C_Ybor_City.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Interior_view_of_cigar_factory%2C_Ybor_City.jpg",
      upstreamArchive: "Boston Public Library, Print Department, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "centro-asturiano-in-ybor-city-florida-13", era: "suburban", year: "circa 1947",
      title: "Centro Asturiano in Ybor City, Florida",
      caption: "Florida Memory's note: the Centro Asturiano at 1913 Nebraska Avenue was built in 1913 as the meeting place of a Latin social club and mutual aid society, and was listed on the National Register of Historic Places in 1974.",
      creator: "Unknown", license: "Public domain",
      creditLine: "Florida Memory / State Archives of Florida, local call number PR12436, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Centro_Asturiano_in_Ybor_City,_Florida_(7899760104).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/Centro_Asturiano_in_Ybor_City%2C_Florida_%287899760104%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/Centro_Asturiano_in_Ybor_City%2C_Florida_%287899760104%29.jpg",
      upstreamArchive: "State Archives of Florida / Florida Memory, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "cuban-cigar-makers-at-work-ybor-city-flo-14", era: "renewal", year: "1974",
      title: "Cuban cigar makers at work, Ybor City, Florida",
      caption: "Hand-rolling survives into the 1970s, decades after mechanisation; Florida Memory dates this image 1974.",
      creator: "Unknown", license: "Public domain",
      creditLine: "State Library and Archives of Florida (Florida Photographic Collection), local call number FS85691, via Wikimedia Commons (public domain)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cuban_cigar_makers_at_work-_Ybor_City,_Florida_(7596637548).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Cuban_cigar_makers_at_work-_Ybor_City%2C_Florida_%287596637548%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Cuban_cigar_makers_at_work-_Ybor_City%2C_Florida_%287596637548%29.jpg",
      upstreamArchive: "State Library and Archives of Florida, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "c-rculo-cubano-de-tampa-the-cuban-club-15", era: "revival", year: "2007",
      title: "Círculo Cubano de Tampa (the Cuban Club)",
      caption: "The Cuban Club, one of the mutual-aid social clubs that anchored Ybor City's immigrant life.",
      creator: "Ebyabe", license: "CC BY 2.5",
      creditLine: "Ebyabe (own work), via Wikimedia Commons (CC BY 2.5)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tampa_Circulo_Cubano01.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Tampa_Circulo_Cubano01.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Tampa_Circulo_Cubano01.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "ybor-square-the-former-ybor-cigar-factor-16", era: "revival", year: "2007",
      title: "Ybor Square (the former Ybor cigar factory), Ybor City",
      caption: "The V.M. Ybor factory complex in its adaptive-reuse life as Ybor Square.",
      creator: "Ebyabe", license: "CC BY 2.5",
      creditLine: "Ebyabe (own work), via Wikimedia Commons (CC BY 2.5)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Tampa_Ybor_City_Ybor_Square01.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Tampa_Ybor_City_Ybor_Square01.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Tampa_Ybor_City_Ybor_Square01.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "the-italian-club-of-tampa-17", era: "waterfront", year: "2014",
      title: "The Italian Club of Tampa",
      caption: "L'Unione Italiana, the Italian Club, on 7th Avenue.",
      creator: "Upstateherd", license: "CC BY-SA 4.0",
      creditLine: "Upstateherd (own work), via Wikimedia Commons (CC BY-SA 4.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Italian_Club_of_Tampa.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/The_Italian_Club_of_Tampa.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/The_Italian_Club_of_Tampa.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "centro-espa-ol-de-tampa-ybor-city-18", era: "waterfront", year: "2015",
      title: "Centro Español de Tampa, Ybor City",
      caption: "Commons description: built as a cultural clubhouse in 1912, the red brick structure at 1526–1536 East 7th Avenue is today part of a shopping and entertainment complex. Pairs directly with the ca. 1914 Florida Memory view.",
      creator: "P. Hughes", license: "CC BY-SA 4.0",
      creditLine: "P. Hughes (User:Indies1), own work, via Wikimedia Commons (CC BY-SA 4.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Centro_Espa%C3%B1ol,_Ybor_City.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Centro_Espa%C3%B1ol%2C_Ybor_City.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Centro_Espa%C3%B1ol%2C_Ybor_City.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "east-7th-avenue-ybor-city-19", era: "waterfront", year: "2024",
      title: "East 7th Avenue, Ybor City",
      caption: "View east down East 7th Avenue from roughly 1611 E 7th Ave.",
      creator: "Pokemonprime", license: "CC BY 4.0",
      creditLine: "Pokemonprime (own work), via Wikimedia Commons (CC BY 4.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:E_7th_Ave,_Ybor_City,_Florida.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a3/E_7th_Ave%2C_Ybor_City%2C_Florida.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a3/E_7th_Ave%2C_Ybor_City%2C_Florida.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "j-c-newman-cigar-co-building-ybor-city-20", era: "waterfront", year: "2024",
      title: "J.C. Newman Cigar Co. building, Ybor City",
      caption: "The J.C. Newman Cigar Co. building (\"El Reloj\") in Ybor City.",
      creator: "OhanaUnited", license: "CC BY 4.0",
      creditLine: "OhanaUnited (own work), via Wikimedia Commons (CC BY 4.0)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:J.C._Newman_Cigar_Co._building.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/J.C._Newman_Cigar_Co._building.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/J.C._Newman_Cigar_Co._building.jpg",
      upstreamArchive: "Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "sanborn-fire-insurance-map-from-tampa-hi-21", era: "boomtown", year: "1889",
      title: "Sanborn Fire Insurance Map from Tampa, Hillsborough County, Florida (sheets 3-4, includes Ybor City)",
      caption: "April 1889 Sanborn fire-insurance sheet for Tampa; the file page states the set includes Ybor City. Useful as the earliest surveyed footprint of the new cigar town, three years after its 1886 founding.",
      creator: "Sanborn Map Company (author not named on the file page)", license: "Public domain",
      creditLine: "Sanborn Map Company; Library of Congress, Geography and Map Division (loc.gov/item/sanborn01352_003)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Sanborn_Fire_Insurance_Map_from_Tampa,_Hillsborough_County,_Florida._LOC_sanborn01352_003-4.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Sanborn_Fire_Insurance_Map_from_Tampa%2C_Hillsborough_County%2C_Florida._LOC_sanborn01352_003-4.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Sanborn_Fire_Insurance_Map_from_Tampa%2C_Hillsborough_County%2C_Florida._LOC_sanborn01352_003-4.jpg",
      upstreamArchive: "Library of Congress, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "interior-of-cigar-factory-tampa-fla-post-22", era: "boomtown", year: "ca. 1910",
      title: "\"Interior of Cigar Factory, Tampa, Fla.\" (postcard)",
      caption: "Colour postcard of a Tampa cigar factory floor, dated ca. 1910 by the archive. Direct file URL returned 429, not 200.",
      creator: "Unattributed on the record", license: "Public domain",
      creditLine: "State Library and Archives of Florida (Florida Memory), call no. PC4534 / PC6069",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:%22Interior_of_Cigar_Factory,_Tampa,_Fla.%22_(11450181244).jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/%22Interior_of_Cigar_Factory%2C_Tampa%2C_Fla.%22_%2811450181244%29.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8d/%22Interior_of_Cigar_Factory%2C_Tampa%2C_Fla.%22_%2811450181244%29.jpg",
      upstreamArchive: "State Library and Archives of Florida (Florida Memory), via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
    { id: "centro-espanol-entrance-spanish-casino-s-23", era: "depression", year: "1933",
      title: "Centro Espanol, entrance (\"Spanish Casino\"), Seventh Avenue, Tampa",
      caption: "HABS documentation of the Centro Espanol entrance. The Commons date field reads 1933; HABS Florida survey dating is often given as 'compiled after 1933', so treat the year as the survey date, not necessarily the exposure date. Direct file URL returned 429.",
      creator: "Historic American Buildings Survey", license: "Public domain",
      creditLine: "Historic American Buildings Survey; Library of Congress (loc.gov/pictures/item/fl0105.photos.052791p)",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Centro_Espanol.jpg",
      thumbUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Centro_Espanol.jpg",
      fullUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Centro_Espanol.jpg",
      upstreamArchive: "Library of Congress / HABS, via Wikimedia Commons",
      thumbStatus: 200, verificationStatus: "CONFIRMED" },
  ],
};
